### ISSUE TITLE
Retrieving of article list is not robust

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#924] opened 2019-08-03 12:23 UTC
with 1.9.4:

```
mwoffliner --mwUrl="https://pl.wikisource.org" --adminEmail="contact@kiwix.org" --format="nopic" --format="novid" --useCache --noLocalParserFallback --redis="/tmp/sockets/redis_5d38243c37a5580e91642377.sock" --outputDirectory="/output"
```

gives

```
[error] [2019-07-25T19:29:42.801Z] Error in retrieved article [Strona:PL_W_klatce.djvu/115]: { code: 'apierror-visualeditor-docserver-http-error',
  info: '(curl error: 28) Timeout was reached',
  '*':
   'See https://pl.wikisource.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
[error] [2019-07-25T19:30:28.468Z] Error in retrieved article [Strona:Antoni_Lange_-_Przekłady_z_poetów_obcych.djvu/34]: { code: 'apierror-visualeditor-docserver-http-error',
  info: '(curl error: 28) Timeout was reached',
  '*':
   'See https://pl.wikisource.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
[error] [2019-07-25T19:39:32.108Z] Error in retrieved article [M._Arcta_Słownik_Staropolski/Wychowanica]: { code: 'apierror-visualeditor-docserver-http-error',
  info: '(curl error: 28) Timeout was reached',
  '*':
   'See https://pl.wikisource.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
[error] [2019-07-25T19:40:16.627Z] Error in retrieved article [Strona:PL_Bolesław_Prus_-_Lalka_Tom1.djvu/078]: { code: 'apierror-visualeditor-docserver-http-error',
  info: '(curl error: 28) Timeout was reached',
  '*':
   'See https://pl.wikisource.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
[error] [2019-07-25T19:40:17.951Z] Error in retrieved article [Strona:Helena_Mniszek_-_Verte_T.2.djvu/8]: { code: 'apierror-visualeditor-docserver-http-error',
  info: '(curl error: 28) Timeout was reached',
  '*':
   'See https://pl.wikisource.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
[error] [2019-07-25T19:40:18.542Z] Error in retrieved article [Poezye_(Rydel)]: { code: 'apierror-visualeditor-docserver-http-error',
  info: '(curl error: 28) Timeout was reached',
  '*':
   'See https://pl.wikisource.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' }
```

More info at https://farm.openzim.org/tasks/5d38243c37a5580e91642377

**Comment by ISNIT0** [comment] 2019-08-06 09:38
I'm unable to reproduce this with article-list scrapes of the same articles :(

**Comment by kelson42** [comment] 2019-08-11 13:26
Lets see if the problem will appeared again.

**Comment by kelson42** [comment] 2019-09-22 02:32
This problem still occurs and has cause the creation of a WPEN ZIM file with only half of the articles in it. See https://farm.openzim.org/tasks/5d775d281d1619754c6a5642. The problem is that API calls to retrieved the list of articles (with details) seems not to be retried properly and if they really fail to be retrieved properly the process should be stopped.

**Comment by ISNIT0** [comment] 2019-09-24 16:09
@kelson42 What does EN_ALL scraping have to do with "Retrieving of article list"?

**Comment by kelson42** [comment] 2019-09-25 06:18
@ISNIT0 This is only a guess that both are related.

**Comment by kelson42** [comment] 2019-09-28 12:33
It is not a guess anymore:
```
$ cat mwoffliner_5d775d281d1619754c6a5642.log | grep "articles from namespace" | cut -f4 -d ' ' | tr -d '[' | tr -d ']' | paste -s -d+ - | bc
2416623
```

... and we should get around 5M. No error is printed.

**Comment by kelson42** [comment] 2019-09-28 12:36
We should print in the log:
* how many articles are retrieved
* how many articles are expected
* Default log should be a bit more clear about the start and stop, something like this:
```
[log] [2019-09-18T04:27:27.292Z] Got [195] articles [article_1_title .. article_n_id] from namespace [0]
```

Of course all of this does not solve the problem but would help to understand what is going on.

**Comment by kelson42** [comment] 2019-09-28 12:41
I have deleted the file in the repo, but still available here http://tmp.kiwix.org/wikipedia_en_all_nopic_2019-09.zim

**Comment by ISNIT0** [comment] 2019-09-30 13:30
Closing in favour of #993 
The current issue is not related to what this ticket was originally about

**Closed by ISNIT0** 2019-09-30 13:30 UTC
Labels: bug, wikimedia
