### ISSUE TITLE
Unable to find appropriate API end-point to retrieve article HTML

### ISSUE THREAD

**Issue by Dban1** [openzim/mwoffliner#1892] opened 2023-08-26 09:24 UTC
Tried running Docker version of mwoffliner on MacOS M1 Pro for Bulbapedia:

```docker run --volume=$(pwd)/out:/out --link=redis:redis --name=mwoffliner -e REDIS="redis://redis" ghcr.io/openzim/mwoffliner \
       mwoffliner --mwUrl="https://bulbapedia.bulbagarden.net"  --adminEmail=admin@domain.com --optimisationCacheUrl=""
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
starting redis-server in the background…
[error] [2023-08-26T09:20:43.894Z] Failed to run mwoffliner after [9s]: {
	"stack": "Error: Unable to find appropriate API end-point to retrieve article HTML\n    at Downloader.setBaseUrls (file:///tmp/mwoffliner/lib/Downloader.js:158:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Module.execute (file:///tmp/mwoffliner/lib/mwoffliner.lib.js:139:5)",
	"message": "Unable to find appropriate API end-point to retrieve article HTML"
}
[error] [2023-08-26T09:20:43.898Z] 

**********

Unable to find appropriate API end-point to retrieve article HTML

**********
```

Is there something wrong with the url I provided? I've been trying for awhile and not sure what I might be inputting wrong here

**Comment by VadimKovalenkoSNF** [comment] 2023-08-26 14:43
@Dban1 mwoffliner is in the middle of re-architecture process, so the 3rd party wiki-s are not supported for now. You can track current progress in this ticket - https://github.com/openzim/mwoffliner/issues/1830

**Comment by kelson42** [comment] 2023-08-27 02:49
@Dban1 We have our side [an official recipe](https://farm.openzim.org/recipes/bulbagarden) in our ZIM farm to scrape Bulbapedia. This recipe has been failing for months our side as well. The reason is clearly given by the error message: MWoffliner relies on API of Bulbapedia to scrape and the necessary API end-points are not available (here we talk about [the VisualEditor action API end-point](https://www.mediawiki.org/w/api.php?action=help&modules=visualeditor)).

We are working to be able from another[ newly available end-point in Mediawiki which is call the REST API](https://github.com/openzim/mwoffliner/issues/1601).  So this ticket is basically a duplicate of it. That said, [although the API seems to be available](https://bulbapedia.bulbagarden.net/w/rest.php/v1/page/Bulbagarden/), [retrieving the HTML seems broken](https://bulbapedia.bulbagarden.net/w/rest.php/v1/page/Bulbagarden/with_html) (maybe a bad configuration in the reverse proxy?).

**Closed by kelson42** 2023-08-27 02:49 UTC
Labels: question

**Comment by Dban1** [comment] 2023-08-28 12:35
@kelson42 I did some digging, does this help?

If the intention is to get HTML data, this seems to fit the bill:
https://bulbapedia.bulbagarden.net/w/api.php?action=parse&page=Main_Page

**Comment by kelson42** [comment] 2023-08-30 02:13
This is pure HTML, we need "sementic" html to be able to treat and process it.

**Comment by Dban1** [comment] 2023-08-31 15:02
@kelson42 I'm not exactly sure what semantic html refers to in this case, but based on some searching it regards the "metadata" of the tags? Could this be it: https://bulbapedia.bulbagarden.net/w/rest.php/v1/page/Pok%C3%A9mon
