### ISSUE TITLE
Identical image

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1513] opened 2021-08-03 19:23 UTC
ZIM: 2021-07 German Wikipedia (Top Articles)

This is possibly the same bug as https://github.com/openzim/mwoffliner/issues/1496

Article: https://de.m.wikipedia.org/wiki/Fibel_(Schlie%C3%9Fe)

![20210803_211019](https://user-images.githubusercontent.com/71934042/128073186-dbfb7925-87a4-4386-8006-38b580cd82eb.jpg)

Note: 2021-07 German Wikipedia (Top Articles) was scraped by mwoffliner 1.11.8

**Comment by Inbefortus** [comment] 2021-08-04 07:36
The problem also persists in 2021-08 English Wikipedia (Top Articles):

Article: https://en.wikipedia.org/wiki/Spanish_Steps

![20210804_092614](https://user-images.githubusercontent.com/71934042/128139781-92e0e72d-5aa9-4ae6-aa84-bc89d0e1f67f.jpg)

2021-07 English Wikipedia 0.8 is alright.

**Comment by kelson42** [comment] 2021-08-04 07:48
> The problem also persists in 2021-08 English Wikipedia (Top Articles):

Code has not been released, this is why you still have the problem in "Spanish_Steps". You can see in the ZIM itself with which version of MWoffliner is has been scraped, see http://library.kiwix.org/wikipedia_en_top_maxi/M/Scraper. I doubt the first reported problem in "Fibel" is a duplicate of #1496.

**Comment by Inbefortus** [comment] 2021-08-04 08:04
> Code has not been released, this is why you still have the problem in "Spanish_Steps".

Okay, that explains it all.

> I doubt the first reported problem in "Fibel" is a duplicate of #1496.

Now that you mention it, I also suspect that it is not the same bug. If it were the same, there wouldn't be the same image three times....

**Comment by kelson42** [comment] 2021-08-06 08:26
I have tried to reproduce the problem with latest version of code base, without success:
![image](https://user-images.githubusercontent.com/1029718/128481051-62e0199b-96ab-4cd9-89a7-475b1a833bc8.png)

We will make a new release of MWoffliner in the next days, hopefully this kind of problem will disappear.

**Closed by kelson42** 2021-08-06 08:26 UTC
Labels: bug, question

**Comment by kelson42** [comment] 2021-08-06 08:29
@Inbefortus I have request a new version of Wikipedia DE TOP to be built with the latest dev version of MWoffliner https://farm.openzim.org/pipeline/33264e17b81f9f20392fc016. You can then check this ZIM file to see if you still see duplicates.

**Comment by Inbefortus** [comment] 2021-08-06 20:16
> @Inbefortus I have request a new version of Wikipedia DE TOP to be built with the latest dev version of MWoffliner https://farm.openzim.org/pipeline/33264e17b81f9f20392fc016. You can then check this ZIM file to see if you still see duplicates.

@kelson42 It looks like the bug has been eliminated specifically in this article. Great. 

If and when I come upon further identical images, I'll let you know here right away!
