### ISSUE TITLE
There is no sign in the References before the link

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1236] opened 2020-07-24 07:59 UTC
In the English Wikipedia, there is a sign (**up arrow**) in the **References** before the link. If you click on it, you can automatically move to a place in the text - **_Jump up_**.
Sample Article: [**Windows Vista**](https://en.wikipedia.org/wiki/Windows_Vista#References):
![Vista-Jump-up](https://user-images.githubusercontent.com/65112331/88370837-84ceed00-cd9b-11ea-8751-9d46f85d9037.gif)

But in **Kiwix** there is no such icon in the **References** before the link:
![Vista-Jump-up-NO-Kiwix-2 8 0](https://user-images.githubusercontent.com/65112331/88370848-8b5d6480-cd9b-11ea-8057-13dfdfd66cb3.png)

The situation is similar with other Wikipedia In particular with **[Russian](https://ru.wikipedia.org/wiki/Windows_Vista#Примечания)** - **_Обратно к тексту_**:
![Vista-ref-ru](https://user-images.githubusercontent.com/65112331/88370866-9617f980-cd9b-11ea-8f51-ebe79a3a7d93.gif)

PS: we are talking about notes that are used **once**!

**Comment by Jaifroid** [comment] 2020-07-24 08:23
@Ubuntu-2020 This is a duplicate of #881.

**Closed** 2020-07-24 08:24 UTC
Labels: duplicate
