### ISSUE TITLE
Spanish Wikipedia scraping failure examples, during every month of 2023

### ISSUE THREAD

**Issue by holta** [openzim/mwoffliner#1833] opened 2023-04-28 19:21 UTC
Examples of https://farm.openzim.org/recipes/wikipedia_es_all failing to complete:

- January 7 ...is likely unrelated as Exit Code 1:
https://farm.openzim.org/pipeline/e24b9badd76dda26941c9b36/debug

- February 10 ...Exit Code 2
https://farm.openzim.org/pipeline/8c80a16ca8a2092778924e36/debug

- March 12 ...Exit Code 2
https://farm.openzim.org/pipeline/d6f160f2321aab6c7161d046/debug

- April 14 ...Exit Code 2
https://farm.openzim.org/pipeline/ccc986bd66e74adf6a206346/debug

**Comment by kelson42** [comment] 2023-05-02 06:51
Duplicate of #1730

**Closed by kelson42** 2023-05-02 06:51 UTC
Labels: bug, duplicate
