### ISSUE TITLE
Wiktionary/Wikivoyage zim databases lag website by five months

### ISSUE THREAD

**Issue by archenemies** [openzim/mwoffliner#1397] opened 2021-02-06 20:46 UTC
I have a Wikitionary Zim file from December 2020, which I downloaded using the GUI kiwix-desktop interface (2020-12-10; "Pictures, Fulltext index"; 5.65 GB).

This works great for me but I'm not sure how to figure out which Wiktionary it is based on.

It lacks changes to Wiktionary made in August 2020, although it contains changes from May 2020.

Where can I find out which Wiktionary dump a Zim file is based on, and how do I find a Zim file which is based on a current version of Wiktionary?

(And where should I submit this issue?)

**Comment by kelson42** [comment] 2021-02-07 09:07
@archenemies BTW, revision id, like revision date are available in the upstream link in the foorter of each article.

**Comment by archenemies** [comment] 2021-02-07 17:25
That's interesting about the upstream link in the footer, well ["rocker"](http://localhost:8080/wiktionary_en_all_maxi_2020-12/A/rocker) has the wrong link

<https://en.wiktionary.org/wiki/?title=rocker&oldid=61038509>

because it points to a revision from 4 November 2020 with the "breve below" sense #4 filled in, but the page that Kiwix serves me lacks that sense.

**Comment by kelson42** [comment] 2021-02-10 12:48
It looks like to be a bug in the Wikimedia REST API because it simply does not deliver the latest version (like you reported). See: https://en.wiktionary.org/api/rest_v1/page/mobile-sections/rocker. This is the root of the bug.

On the `mwoffliner` side, there is a weakness which is that we don't request a specific revisionid, but just take the latest. If we would retrieve https://en.wiktionary.org/api/rest_v1/page/mobile-sections/rocker/61774146, then we would have get the proper content.

I will do the necessary on both sides to improve the situation.

**Comment by kelson42** [comment] 2021-02-10 13:09
A bug ticket has been open upstream at https://phabricator.wikimedia.org/T274359

**Comment by kelson42** [comment] 2021-02-10 13:24
@MananJethwani Here again this is "complicated" to change due to the architecture.

**Comment by archenemies** [comment] 2021-02-10 18:03
@kelson42 Thank you so much for tracking that down and re-reporting the bug

**Comment by Jaifroid** [comment] 2021-09-23 10:31
Just to track and keep this issue fresh, it is still impossible to open the article "Cambridge" from the 2021-09 English Wikivoyage ostensibly due to this bug. (Cambridge is a major tourist destination pre- and post-pandemic, so it is a quite serious upstream bug!)

**Comment by kelson42** [comment] 2021-12-05 10:17
See as well https://phabricator.wikimedia.org/T226931. It seems there is a momentum these days to fix it upstream...

**Comment by Jaifroid** [comment] 2021-12-17 16:31
"Cambridge" still inaccessible in the December Wikivoyage in English... The lag hasn't caught up yet...

**Comment by Jaifroid** [comment] 2022-05-07 10:07
@kelson42  "Cambridge (England)" article is STILL inaccessible in `wikivoyage_en_all_maxi_2022-05.zim`. Can there really be a 15-month time lag? No movement on the Phabricator ticket since December 2021.

Is there any conceivable workaround we can introduce on our side?

**Comment by kelson42** [comment] 2022-05-07 10:34
@Jaifroid Funny that you come back on this ticket today, 2 days ago something happened related to this bug... might be fixed in a near future at Wikimedia... but too early to be sure.

**Comment by Jaifroid** [comment] 2022-05-07 12:17
It's because I'm preparing the next Wikivoyage release, so I checked again. Thanks for the update! Fingers crossed...

**Comment by Jaifroid** [comment] 2022-05-08 20:50
Just to add some more data points, and something very strange which suggests the issue is not only with the API:

I made major updates to the article https://en.wikivoyage.org/wiki/Santa_Cruz_de_Mompox on 15th April.  On 22nd April, a new Wikivoyage ZIM was created that did not contain these updates. I subsequently checked the REST API version https://en.wikivoyage.org/api/rest_v1/page/html/Santa_Cruz_de_Mompox, and it was the updated version.

I fully expected the May Wikivoyage, published on 4th May, to reflect these updates. However, it still shows the out-of-date version. Curiously, the footer points to https://en.wikivoyage.org/wiki/?title=Santa_Cruz_de_Mompox&oldid=4430914 , which **is** the updated version last edited 17th April, but the actual text scraped is a previous version, prior to my changes.

How can this be? Why does the footer point to a recent update, but the text does not correspond to that update?

**Comment by Jaifroid** [comment] 2022-06-05 13:55
@kelson42 Unfortunately, it is still not possible to open the article "Cambridge (England)" in `wikivoyage_en_all_maxi_2022-06.zim` which was scraped in the last couple of days. Also, the article "Santa Cruz de Mompox" is still the old version prior to the major edits I myself made on 15th April this year. Additionally, the footer of our scraped page directs to an updated version of the article (in history) which is NOT the one contained in our scrape.

Compare:

* https://library.kiwix.org/wikivoyage_en_all_maxi_2022-06/A/Santa_Cruz_de_Mompox (June 2022 scrape)
* https://en.wikivoyage.org/wiki/Santa_Cruz_de_Mompox (online)

You will notice missing images in our scrape, and the lede is completely different. HOWEVER; if I click on the footer link in our scrape, it points to https://en.wikivoyage.org/wiki/?title=Santa_Cruz_de_Mompox&oldid=4430914 which is the supposedly updated version. This is NOT the version that has been scraped.

So either the footer information is incorrect or something very strange is going on.

**Comment by kelson42** [comment] 2022-06-05 16:45
@Jaifroid Thx for testing that. I launched the scrap manualy earlier as I though I will get a feedback from you. I will need the information upstream.

**Comment by kelson42** [comment] 2022-06-08 08:53
@Jaifroid I tested myself and full confirm the bug is still there and reported it upstream accordingly.

**Comment by xinxinxinxinxin** [comment] 2022-07-11 11:06
Hello, I have similar problem with French Wikivoyage.

A page created in February 2022 is in the June file: https://library.kiwix.org/wikivoyage_fr_all_maxi_2022-06/A/Mont-Saint-Hilaire https://fr.wikivoyage.org/w/index.php?title=Mont-Saint-Hilaire&oldid=502132

But changes made in January 2020 are not in this file: https://library.kiwix.org/wikivoyage_fr_all_maxi_2022-06/A/Voyager_en_autocar_en_France https://fr.wikivoyage.org/w/index.php?title=Voyager_en_autocar_en_France&oldid=464098

**Comment by Jaifroid** [comment] 2022-07-19 05:52
Issues identified above persist in July Wikivoyage `wikivoyage_en_all_maxi_2022-07.zim`. 'Cambridge (England)' article still not accessible at all, and article on 'Mompox' doesn't reflect extensive changes made on 22nd April. At least the footer now correctly identifies the Mompox article as the version last edited on 17th April, before these changes, which is something...

**Comment by Jaifroid** [comment] 2022-10-23 14:49
Thanks for the update. I came here just to note that the issues mentioned above still persist in `wikivoyage_en_all_maxi_2022-10.zim`... Just to prevent this issue form being marked as stale.

**Comment by Jaifroid** [comment] 2023-01-01 13:11
Issues persist in `wikivoyage_en_all_maxi_2022-12.zim`. They were supposed to have been fixed by https://phabricator.wikimedia.org/T274359, but my examples of the Cambridge (England) and the Mompox articles clearly show that the issue persists. The former continues to be inaccessible two years on, and the Mompox article still shows old information that was edited extensively over 8 months ago.

**Comment by kelson42** [comment] 2023-01-01 13:18
Yes, problem is still there but upstream :(

**Comment by Jaifroid** [comment] 2023-01-01 14:12
Actually, I noticed that https://en.wikivoyage.org/api/rest_v1/page/mobile-sections/Cambridge is producing the outdated disambiguation page, whereas https://en.wikivoyage.org/api/rest_v1/page/mobile-html/Cambridge is producing the correct article. Therefore, in the case of the Cambridge article at least, the problem is that we are using the deprecated mobile-sections API instead of the mobile-html API, i.e. the issue is #1664, and it's no longer upstream.

However, in the case of the Mompox article, https://en.wikivoyage.org/api/rest_v1/page/mobile-html/Santa_Cruz_de_Mompox is still producing an outdated version, so the issue is upstream for that page.

**Comment by kelson42** [comment] 2023-01-01 14:19
@Jaifroid If we fell lucky, implementing #1664 will help to fix the problem then.

**Comment by Jaifroid** [comment] 2023-01-01 14:21
It looks like it would in some cases at least...

**Comment by Jaifroid** [comment] 2023-01-29 18:00
A slight advance: the article `Cambridge (England)` is now accessible in the January 2023 Wikivoyage!
However, the article `Mompox` is still showing an outdated version, despite the upstream fix. I guess clearing the caches upstream didn't work.

**Comment by Jaifroid** [comment] 2023-01-30 22:50
I know this is just adding more examples, but just to underline the gravity of this issue, now almost anywhere I look in the latest English Wikivoyage ZIM (`01_2023`), I find pages that claim to be scrapes of a recent version, but in fact are out of date by a year or more and contain increasingly useless information. Here's another example, the "Argentina" article. The link at the foot of the page takes us to a revision last made 2nd January 2023, but in fact the scraped text does not at all correspond to this version. As can be seen below (ZIM on left, 2-Jan-23 version on right), there is a seriously outdated info panel saying that entry to Argentina is heavily restricted due to COVID-19.

At this point, it's not possible to recommend travelling with the latest Wikivoyage ZIMs!

Do we have a timeline on switching to the new API? It is becoming quite urgent, unfortunately.

<img alt="image" src="https://user-images.githubusercontent.com/4304337/215612866-329ccc1e-b20c-4f07-838b-55be41988c97.png">

**Comment by Jaifroid** [comment] 2023-02-07 21:21
It looks like this may finally be fixed in principle: see https://phabricator.wikimedia.org/T226931. The caveat is that articles will only get updated once they are edited after today, in which case the mobile-sections endpoint for the article should update. If an article is not edited since the fix, then the cache won't be changed, and it will still continue to serve out-of-date content.

**Comment by kelson42** [comment] 2023-02-07 21:22
@Jaifroid They should purge the full cache, otherwise our bug won't be fixed.

**Comment by Jaifroid** [comment] 2023-02-07 21:25
Well, I agree, but the maintainers are being cautious and want to watch the change for a couple of weeks to make sure they haven't introduced a regression. I think we can push for a full cache purge if everything seems OK...,

**Comment by Jaifroid** [comment] 2023-02-19 08:48
I'm happy to report that the latest English Wikivoyage (February 2023) is now showing the latest revision for the article on Mompox (one of my test articles). I updated that page after the fix in https://phabricator.wikimedia.org/T226931, as a test, and it's pleasing to see that the fix has worked and made it into the Wikivoyage ZIM. Additionally, the dated COVID-19 warning no longer appears on the Argentina country page, though it still appears on some other Latin American country pages (e.g. Colombia). This is because some pages will have been edited since the fix, and others not yet. Even a null edit will, apparently, update the cache now.

It would be worth testing Wiktionary pages that have been updated since round about 8th February. After confirmation, I think this issue could be closed.

**Comment by kelson42** [comment] 2023-02-19 08:50
@Jaifroid Shoukd I restart a specific scrape for wiktionary?

**Comment by Jaifroid** [comment] 2023-02-19 08:58
@kelson42 The last English Wiktionary scrape appears to be 31st October 2022 (at least that's the last one on download.kiwix.org), so yes, it would be good to try to get a new scrape if possible, though we could test other languages if we can identify a page updated since 8th Feb (or update a page manually with a minor edit). It might be worth doing this in a controlled way: make a minor edit to a page we know to be problematic, then run the scrape?

**Comment by kelson42** [comment] 2023-02-19 10:14
@Jaifroid You are in lead, let me just what do do.

**Comment by Jaifroid** [comment] 2023-02-19 10:16
OK, I'll edit one of the reported pages above and will let you know when done so you can initiate a scrape.

**Comment by kelson42** [comment] 2023-02-22 19:20
@Jaifroid any new recipe to relaunch?

**Comment by Jaifroid** [comment] 2023-02-22 20:10
Sorry, I realized I would have to download the latest available Wiktionary archive to find an article that is not updated... Nearly there.

**Comment by Jaifroid** [comment] 2023-02-22 20:21
@kelson42 OK, I've made a minor edit (adding a derived word) to the `rocker` article mentioned above, which appears to be still outdated in the latest Wikivoyage we have, and had been like that since first reported above.

So you could run a new scrape of English Wikivoyage. We need a new one in any case, since the last one is a bit old now.

**Comment by Jaifroid** [comment] 2023-02-22 20:21
@kelson42 Please note I meant WIKTIONARY, not Wikivoyage!

**Comment by danielzgtg** [comment] 2023-02-22 21:00
Also something seems to be up these days with https://download.kiwix.org/zim/wiktionary/ . The last nopics were 2022-10 and 2022-09 and the last maxis were 2022-09 and 2022-07. The nopic used to be released every month, and the maxi used to be every 3 months. I use the maxi zims, but it's already 2023-02 now.

**Comment by Jaifroid** [comment] 2023-02-22 21:25
@danielzgtg There was an issue about this here: https://github.com/openzim/mwoffliner/issues/1789. It's been fixed very recently (fingers crossed).

**Comment by kelson42** [comment] 2023-02-23 13:26
@Jaifroid Actually I have checked and your revision is delivered properly by the API, see https://en.wiktionary.org/api/rest_v1/page/mobile-sections/rocker. Closing the ticket.

**Closed by kelson42** 2023-02-23 13:26 UTC
Labels: upstream, wikimedia
