### ISSUE TITLE
 Missing (broken?) images in latest en zim

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#462] opened 2018-12-12 07:42 UTC
_From @jargony on December 11, 2018 19:40_

In the latest enwiki zim file, wikipedia_en_all_novid_2018-10, images are broken in some articles. It is true for several large articles. Se attached image.

![united states](https://user-images.githubusercontent.com/45800554/49825499-e12af780-fd84-11e8-9243-338c98edfa51.png)

_Copied from original issue: kiwix/kiwix-desktop#74_

**Comment by kelson42** [comment] 2018-12-12 07:42
_From @mossroy on December 11, 2018 19:47_

I confirm this issue

**Comment by kelson42** [comment] 2018-12-12 07:42
It is a problem in the ZIM file, moving the ticket to mwoffliner.

**Comment by kelson42** [comment] 2018-12-12 07:44
We have this kind of problem since the beginning of creating ZIM file. It might be a problem with mwoffliner or with zimwriterfs... but more probably with mwoffliner. @ISNIT0 you have I think improve the content downloader in 1.6, what is your opinion on this kind of problem?

**Comment by ISNIT0** [comment] 2018-12-12 14:37
@kelson42 I don't think the downloader was changed much in 1.6, I'll take a look at the ZIM file soon.

**Comment by Jaifroid** [comment] 2019-01-18 08:21
I've had a report (by email) that concerns this issue with this ZIM (in Kiwix JS Windows). I post with the user's permission:

> Kiwix JS [Windows] works perfectly well, on Wikipedia 'nopic', but just keeps falling over on the larger 'novid' file... it will load the file, random sometimes finds a page, sometimes not. The index seems OK - you can find the page desired, but then it just goes blank.
> 
> Anyway, that's how it is for me with the huge wikipedia_en_all_novid_2018-10.zim
> 
> I tried with the blue box show pictures on demand setting (brilliant idea) but the same - some pages do, and some don't.
> 
> And it's consistent, so must be something about the pages that won't load.
> 
> examples: 'Badger' loads fine, 'L'arlesiana' does not load.

I've pointed the user to this issue, and as a result he has downloaded `wikipedia_en_all_novid_2018-06.zim`, and confirms that the problems do not appear with that ZIM. I thought I'd add this report, as I believe it confirms that `wikipedia_en_all_novid_2018-10.zim` is a particularly bad encode and should probably be removed. Having said that, clearly Kiwix JS Windows should handle this situation a bit better.

**Comment by kelson42** [comment] 2019-02-01 10:22
@ISNIT0 Without any additional information, this is a duplicate of #496. So don't worry about it, it is in the milestone just to keep track.

**Comment by ISNIT0** [comment] 2019-02-11 17:18
As this is a duplicate of #496, I'm going to mark it as closed

**Closed by ISNIT0** 2019-02-11 17:18 UTC
Labels: bug
