### ISSUE TITLE
Enhancement - Zim Tags

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#129] opened 2017-08-26 14:15 UTC
Please implement the IIAB recommendations in kiwix/kiwix-tools#71

**Comment by kelson42** [comment] 2017-08-26 15:05
I need a bit time on this as this is not IIAB specific - of course.

**Comment by kelson42** [comment] 2019-05-11 18:46
Duplicate of kiwix/kiwix-tools#71

**Closed by kelson42** 2019-05-11 18:46 UTC
Labels: enhancement
