### ISSUE TITLE
Missing h1 article heading if customMainPage is not the exactly articleId

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1322] opened 2020-12-06 18:10 UTC
For example, with the `wikipedia_en_ray_charles_maxi_2020-12.zim`, none of the articles have the h1 header at the top of the page (see screenshot of article from December ZIM [top] compared with article for November ZIM [bottom]).

With `wikipedia_en_computer_maxi_2020-12.zim` some articles have h1 and others don't.

**Ray Charles December 2020:**

![image](https://user-images.githubusercontent.com/4304337/101288306-c9f53800-37ed-11eb-9c94-30c3e190f6bb.png)

**Ray Charles November 2020:**

![image](https://user-images.githubusercontent.com/4304337/101288355-0c1e7980-37ee-11eb-9312-e72781028210.png)

**Comment by kelson42** [comment] 2020-12-07 15:47
@MananJethwani any idea what happened here? Curious to know how we missed such a serious regression.

**Comment by MananJethwani** [comment] 2020-12-07 16:10
yeah I am looking into it rn.....

**Comment by MananJethwani** [comment] 2020-12-08 19:34
this is because of renderMcsArticle and url
the bad architecture you mentioned is causing this,
details in mobileRestApi has a lead section in json where as
desktopRestApi doesn't
and when we use desktopRestApi as in case of current requests, lead-section-wrapper is not called and we don't have a heading
another thing is when we are checking for baseUrls mobileRestApi is available still it is not detected as it considers empty string as a bad request and fails
so there are multiple ways of solving this issue
1) we can add a title to body in case of desktopRestApi or other  cases which don't add lead section
2) we can correct the baseUrlRequest and add some string to secure that detection works fine

IMO we should implement both of them

**Comment by kelson42** [comment] 2020-12-09 14:49
This is basically a duplicate of #1318. The only difference is that the problem with #1318 is an uppercase/lowercase problem.

**Closed** 2020-12-12 13:56 UTC
Labels: bug
