### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by benoit74** [openzim/mwoffliner#1998] opened 2024-03-01 08:20 UTC
[vikidia_scn](https://farm.openzim.org/recipes/vikidia_scn) is failing with `Error parsing article .to` with an inner error `Cannot read properties of undefined (reading 'replace')`. 

```
[error] [2023-10-27T22:00:52.969Z] Error parsing article .to
[error] [2023-10-27T22:00:52.970Z] Failed to run mwoffliner after [11s]: {
	"stack": "TypeError: Cannot read properties of undefined (reading 'replace')\n    at interpolateTranslationString (file:///tmp/mwoffliner/lib/util/misc.js:139:31)\n    at templateArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:860:21)\n    at processArticleHtml (file:///tmp/mwoffliner/lib/util/saveArticles.js:389:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async saveArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:158:61)\n    at async Promise.all (index 0)\n    at async file:///tmp/mwoffliner/lib/util/saveArticles.js:147:30",
	"message": "Cannot read properties of undefined (reading 'replace')"
}
[error] [2023-10-27T22:00:52.970Z] 

**********

Cannot read properties of undefined (reading 'replace')

**********
```

**Comment by kelson42** [comment] 2024-06-28 18:09
See https://github.com/openzim/mwoffliner/pull/2050#issuecomment-2197390148

**Comment by kelson42** [comment] 2024-06-28 20:46
This is a duplicate of #2046, but Vikidia scraping suffers of other problems.

**Closed by kelson42** 2024-06-28 20:46 UTC
Labels: bug
