### ISSUE TITLE
Some page's main content contains externel links

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1437] opened 2021-04-10 10:41 UTC
In the article "No-till_farming", the main picture is not displayed, and there are some failed external link during the loading process:

https://upload.wikimedia.org/wikipedia/commons/2/23/Icons-mini-file_acrobat.gif
https://upload.wikimedia.org/wikipedia/commons/6/65/Lock-green.svg
https://upload.wikimedia.org/wikipedia/commons/d/d6/Lock-gray-alt-2.svg
http://127.0.0.1:8181/wikipedia_en_all_maxi/I/m/NRCSMD83008_-_Maryland_(4535)(NRCS_Photo_Gallery).jpg.webp

And these failed links keep the loading icon running until the failure.

**Comment by kelson42** [comment] 2021-04-10 13:57
Duplicate of #1280

**Closed by kelson42** 2021-04-10 13:57 UTC
Labels: bug, duplicate
