### ISSUE TITLE
Missing images in 2021-08 Nap Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1530] opened 2021-08-22 17:55 UTC
![Screenshot_20210822-195136_Kiwix](https://user-images.githubusercontent.com/71934042/130365048-516b36b8-e5e3-4e4d-9ee8-c1a733f6e934.jpg)
![Screenshot_20210822-195142_Kiwix](https://user-images.githubusercontent.com/71934042/130365050-8687a482-758f-469f-b6aa-402b3b82ded3.jpg)
![Screenshot_20210822-195146_Kiwix](https://user-images.githubusercontent.com/71934042/130365051-e0f6816e-c91f-4c77-95a4-06f10034b8e9.jpg)
![Screenshot_20210822-195403_Kiwix](https://user-images.githubusercontent.com/71934042/130365097-8dc35236-0de4-44f4-972b-805755aa757d.jpg)

A̵n̵d̵ ̵m̵u̵c̵h̵ ̵m̵o̵r̵e̵.

**Comment by kelson42** [comment] 2021-08-22 18:17
An you please give the link to the zim file?

**Comment by Inbefortus** [comment] 2021-08-22 18:41
@kelson42 https://mirror.download.kiwix.org/zim/wikipedia/wikipedia_nap_all_maxi_2021-08.zim

https://farm.openzim.org/pipeline/ec14785d21baf3bd05e22216

**Comment by kelson42** [comment] 2021-08-22 19:09
Btw, I see no problem with the 3 first screenshots. No available picture online, no available picture offline.

**Comment by kelson42** [comment] 2021-08-22 19:15
Will have a look to understand why picture is missing in article "Maleo".

**Comment by Inbefortus** [comment] 2021-08-22 19:29
> Btw, I see no problem with the 3 first screenshots. No available picture online, no available picture offline.

@kelson42 You're right. My bad. To me, it looked like it was missing. I should have looked at the original as well.

**Comment by Inbefortus** [comment] 2021-08-22 20:21
@kelson42 If this helps somehow:

Another article with missing image:
https://nap.wikipedia.org/wiki/Craveggia

![Screenshot_20210822-220335_Kiwix](https://user-images.githubusercontent.com/71934042/130368692-bc6880e9-fd19-4044-88f4-32faff50761b.jpg)

Log with the reference to the missing image:

![20210822_220620](https://user-images.githubusercontent.com/71934042/130368707-33607e1f-5b84-416f-b2c0-efe20946a09e.png)

The missing image on Commons:

![Screenshot_20210822-220714_Samsung Internet](https://user-images.githubusercontent.com/71934042/130368755-ca407f2d-e385-4d1e-8085-4eb7334d5f21.jpg)

If you click on the filename of the image, you will get to this page, which indicates that the name of the missing image is different from the one in the logs:

![Screenshot_20210822-220729_Samsung Internet](https://user-images.githubusercontent.com/71934042/130368827-f9019099-fd60-4f3a-bae2-7de6603df681.jpg)

Clicking on the link will take you to the missing image, again with a different file name than in the logs:

![Screenshot_20210822-220737_Samsung Internet](https://user-images.githubusercontent.com/71934042/130368937-c3c77143-79a7-4f22-99e9-3d285281a392.jpg)

**Comment by Inbefortus** [comment] 2021-08-24 20:38
@kelson42 It seems that every Wikipedia is harmed by "Not able to download content due to Error: Request failed with status code 404".

For example, opening 

https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Queen_Suthida_in_6_April_2020.jpg/130px-Queen_Suthida_in_6_April_2020.jpg 

gives:

![Screenshot_20210824-223454_Samsung Internet](https://user-images.githubusercontent.com/71934042/130686484-f7498635-6a04-4fb8-90e4-4a7d4b2d08d6.jpg)

**Comment by kelson42** [comment] 2021-08-25 04:45
@Inbefortus Yes, 404 is normal if you retrieve an image/thumbnail which does not exist (anymore).

**Comment by kelson42** [comment] 2021-08-28 13:57
Yes, this is an upstream problem, this is easily verifiable by checking the API output:
* https://nap.wikipedia.org/api/rest_v1/page/html/Maleo
* https://nap.wikipedia.org/api/rest_v1/page/html/Craveggia

This is something you can check easily yourself and that I invite you to do to easily identify if the problem is upstream (in Wikimedia backend) or in MWoffliner. I'm happy to track here in both case, but this help then to go forward with the analysis.

Another recommendation (or request on my side) would to be careful with hopening a ticket with many examples sharing the same sympton... even if this is not fundamentatly wrong. The reason is that it forces us/me to make the analysis on all of them. Either they share the same root cause analysis (this seems to be the case here, luckily) and I just "loose" time or there are different root causes and then the ticket needs to be splitted. I would prefer if you could open with one example, let me do the analysis, and them you verify afterwards if the other cases you have found are other scenarios (then opening a new ticket) or the same. Thank you in advance for your understanding.

**Comment by kelson42** [comment] 2021-08-28 14:00
@Inbefortus You are right about your analysis, in both cases, we have redirected images:
* https://commons.wikimedia.org/w/index.php?title=File:Maleo-Italy-Arco-Trecchi.JPG&redirect=no
* https://commons.wikimedia.org/w/index.php?title=File:Craveggia_-_sullo_sfondo_il_Monte_Rosa.jpg&redirect=no

**Comment by kelson42** [comment] 2021-08-28 14:04
@Inbefortus After searching a bit I discovered that this ticket is a duplicate of #1019, this is an old bug on Wikipedia side :(

**Closed by kelson42** 2021-08-28 14:04 UTC
Labels: upstream, wikimedia
