### ISSUE TITLE
The same number of articles in different ZIM files

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1645] opened 2022-07-18 17:43 UTC
**wikipedia_ru_all_maxi_2021-03**: **1 636 223 articles**
![Number-of-articles](https://user-images.githubusercontent.com/65112331/179570442-70c57db5-da87-46de-b723-b3d9de0bd031.gif)

**[wikipedia_ru_all_maxi_2022-06](http://library.kiwix.org/wikipedia_ru_all_maxi_2022-06/A/Участник:The_other_Kiwix_guy/Landing)**: **1 636 223 articles**
![library-kiwix](https://user-images.githubusercontent.com/65112331/179570463-924b068b-506a-401e-815f-b9c3fa4e8b86.png)

How is this possible?
Is it a bug?

**Comment by kelson42** [comment] 2022-07-18 19:31
Duplicate of #1535

**Closed by kelson42** 2022-07-18 19:31 UTC
