### ISSUE TITLE
Wikisource_ru - Categorytree error

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1432] opened 2021-04-05 14:34 UTC
**Categorytree** in **Wikisource_ru** is not displayed correctly in Kiwix.
`{{#categorytree:Словарные статьи Владимира Владимировича Лермантова|mode=pages|depth=0}}`
Article about **[physicist in ru.wikisource](https://ru.wikisource.org/wiki/Владимир_Владимирович_Лермантов)**:
![wikisource-web](https://user-images.githubusercontent.com/65112331/113584863-19306580-9634-11eb-8a7c-44213c4d6d6b.gif)

Article about **[physicist in kiwix-wikisource](http://library.kiwix.org/wikisource_ru_all_nopic_2021-03/A/Владимир_Владимирович_Лермантов)**, and also there is no picture.:
![wikisource-kiwix](https://user-images.githubusercontent.com/65112331/113585152-817f4700-9634-11eb-8d95-b2de1cbc2715.gif)

**Comment by MananJethwani** [comment] 2021-04-05 15:09
Most probably a duplicate of #1360

**Closed** 2021-04-05 15:47 UTC
Labels: bug, duplicate, wikimedia
