### ISSUE TITLE
Unable to open the article "Cambridge" from latest English Wikivoyage (2021-08)

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1526] opened 2021-08-15 05:48 UTC
Clicking on a link to "Cambridge" (e.g. on the article "Cambridgeshire"), or loading it from the title list, leads to the disambiguation page. But then clicking on "Cambridge (England)" on the disambiguation page leads back to the disambiguation page. I have not found a way to get to the underlying article "Cambridge (England)". I have tested this on:

* `wikivoyage_en_all_maxi_2021-07.zim`
* `wikivoyage_en_europe_nopic_2021-08.zim`

On Wikivoyage online (English), the title "Cambridge" leads to "Cambridge (England)", not to "Cambridge (disambiguation)".

This issue has occurred relatively recently. I have many times in the past used "Cambridge" as a test page (since I live there!).

**Comment by kelson42** [comment] 2021-08-15 06:52
I see the problem at http://library.kiwix.org/wikivoyage_en_all_maxi/A/Cambridge. There is probably nothing MWoffliner can do. Either the articles have been changed during the scrape or this is the consequence of caching issues at Wikimedia side. Will verify.

**Comment by Jaifroid** [comment] 2021-08-15 07:47
Thank you @kelson42. Because the issue is in both the `2021-07` ZIM and the `2021-08`, I doubt it could be a caching issue or that the article changed during the scrape. I wonder if it might be an issue with following redirection? Maybe mwoffliner only follows one level of redirection? A lot of the links are to "Cambridge (England)", which redirects to "Cambridge".

**Comment by kelson42** [comment] 2021-08-15 15:57
Like I said the API does not deliver the latest version:
https://en.wikivoyage.org/api/rest_v1/page/mobile-sections/Cambridge

**Comment by kelson42** [comment] 2021-08-15 16:06
This is caused by https://phabricator.wikimedia.org/T226931

**Comment by kelson42** [comment] 2021-08-15 16:14
Duplicate of https://github.com/openzim/mwoffliner/issues/1397

**Closed by kelson42** 2021-08-15 16:14 UTC
Labels: upstream, wikimedia
