### ISSUE TITLE
Missing elements from WP0.8 Landing page

### ISSUE THREAD

**Issue by ghost** [openzim/mwoffliner#1009] opened 2019-10-28 13:44 UTC
The page's text refers to [a navbox](https://en.wikipedia.org/wiki/Wikipedia:Version_0.8) that is actually missing from the zim
http://library.kiwix.org/wikipedia_en_wp1-0.8_nopic_2019-10/A/Wikipedia:Version_0.8

**Comment by kelson42** [comment] 2019-10-30 16:36
I confirm

**Comment by bakshiutkarsha** [comment] 2020-04-28 10:48
Can someone please update the example, as the mentioned link for the zim above currently does not seems to exists?

**Comment by kelson42** [comment] 2020-05-04 18:05
@bakshiutkarsha We have permalinks (just remove the date part):
http://library.kiwix.org/wikipedia_en_wp1-0.8_nopic/A/Wikipedia:Version_0.8

**Comment by bakshiutkarsha** [comment] 2020-05-26 07:46
The problem here is the navbox is present in DOM, but because of this style :
```
.content .navbox{
 display: none! important
}
```
it is getting hidden. 
I am still trying to figure out why this style was written and what would be the impact of it if I change it. Are there other cases for which the navbox doesn't shows up, or we have this one case only?

**Comment by kelson42** [comment] 2020-09-02 14:37
Might be a duplicate of  #1033

**Comment by kelson42** [comment] 2021-03-20 06:40
@MananJethwani I believe this might be fixed (with the fix about collapsing boxes) or do we have an other root cause?

**Comment by MananJethwani** [comment] 2021-04-14 15:41
I suppose there is some other cause will start looking into it

**Comment by kelson42** [comment] 2023-01-01 11:52
The problem seems clearly, that mobile upstream does not seems to deliver it (or hide it).

**Comment by kelson42** [comment] 2023-01-20 17:59
This ZIM file is not generated again. Closing.

**Closed by kelson42** 2023-01-20 17:59 UTC
Labels: bug, wikimedia
