### ISSUE TITLE
Some nested references are not handled correctly

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#62] opened 2017-04-21 09:48 UTC
Notes are like references and usually appear at the end of the article:
![capture d ecran 2017-04-21 a 10 48 55](https://cloud.githubusercontent.com/assets/21675885/25272172/30d6cbf0-2687-11e7-926e-f5e416bf23a6.png) 
(that's the view on es.wikipedia.org)

But in the zim file a (truncated) note appears directly into the article:
![capture d ecran 2017-04-21 a 10 42 31](https://cloud.githubusercontent.com/assets/21675885/25272199/4b020b0c-2687-11e7-9d7f-34c204e98107.png)
(some parts are missing, it starts much earlier than the ""y diversas publicaciones gubernamentales". There are other notes in the article but they do not seem to have that issue.

**Comment by bradyhunsaker** [comment] 2018-07-08 16:09
The text is already incorrect from Parsoid, so it does not appear to be a mwoffliner issue:
https://es.wikipedia.org/api/rest_v1/page/html/Espa%C3%B1a

I can't tell whether this is an error in Parsoid, or whether the input is malformed and it is just that the PHP parser on the web happens to handle it "correctly".  The input wikitext is complex, roughly of the form:
{{Refn|...
  \<ref\>{{Cita web|... {{foo}} }}
  \</ref\>
  \<ref\>{{Cita web|...}}
  \</ref\>
  ...
and continuing with 11 total \<ref\>s inside the \<refn\>.

Parsoid appears to interpret the end of one of the {{Cita web}} as the end of the {{Refn}}.

@kelson42 There are some open issues around \<ref\> parsing for Parsoid, but none of them look quite like this issue to me.  I suggest opening an issue there and closing this one.

**Comment by kelson42** [comment] 2018-07-08 16:48
@bradyhunsaker We need to keep track somehow of Parsoid/Mediawiki errors impacting MWoffliner users... otherwise we keep opening duplicate bugs here and keep providing bad user experience.

 On the top of that Parsoid developers, here represented by @subbuss are usually quite reactive to fix problems.

I have created a label, to help to group them.... I tag this issue.

But if I would not close that one, this is really important to create/follow the issue on the side of Parsoid (http://phabricator.wikimedia.org/) and link both tickets.

**Comment by subbuss** [comment] 2018-07-09 03:53
Filed https://phabricator.wikimedia.org/T199070

**Comment by kelson42** [comment] 2018-09-17 09:55
@ISNIT0 We should be able now to close that one, you confirm?

**Comment by kelson42** [comment] 2020-04-25 12:22
The problem is still there http://library.kiwix.org/wikipedia_es_all_maxi/A/Espa%C3%B1a

**Comment by kelson42** [comment] 2021-03-18 14:22
Upstream ticket has been fixed https://phabricator.wikimedia.org/T199070. Waiting to see effect on production.

**Comment by kelson42** [comment] 2021-03-19 07:18
@arlolra Indeed. Thx again for the fix

**Closed by kelson42** 2021-03-19 07:18 UTC
Labels: upstream, wikimedia
