### ISSUE TITLE
The zim file is not up-to-date

### ISSUE THREAD

**Issue by leanhdung1994** [openzim/mwoffliner#1452] opened 2021-05-01 06:57 UTC
I'm using `wiktionary_en_all_maxi_2021-03.zim`. The entry `tease out` has only 2 items.
![image](https://user-images.githubusercontent.com/28704090/116774167-02c2d180-aa5b-11eb-80c6-e24989b229d7.png)
Whereas from the rest api link https://en.wiktionary.org/w/rest.php/v1/page/tease_out/html, it contains all 3 items.
![image](https://user-images.githubusercontent.com/28704090/116774183-26861780-aa5b-11eb-80f8-0ec76249ca58.png)
This is weird because the last edit of this entry is in 2020.

**Comment by kelson42** [comment] 2021-05-01 07:22
Duplicate of #1397

**Closed** 2021-05-01 07:22 UTC
Labels: duplicate, upstream, wikimedia
