### ISSUE TITLE
JS errors in the console: broken jsConfigVars, mw is not defined

### ISSUE THREAD

**Issue by lidel** [openzim/mwoffliner#1034] opened 2020-02-28 19:17 UTC
> @kelson42 I was not sure if this is the right repo – feel free to transfer it to the right one.

Bug found in: [`wikipedia_tr_all_maxi_2019-12.zim`](https://download.kiwix.org/zim/wikipedia/wikipedia_tr_all_maxi_2019-12.zim)

Opening an article produces errors in browser console:

![](https://user-images.githubusercontent.com/24030/75550404-be3c4000-5a29-11ea-9f28-cdeaccc1606c.png)

This seems to be issue with data in ZIM itself: it includes broken JS files.

For example content of  `-/j/js_modules/jsConfigVars.js` is just the left bracket:

```
(
```

### References

- similar errors seems to be mentioned in past:
  - https://github.com/kiwix/kiwix-js/pull/587#issuecomment-583804029

**Comment by kelson42** [comment] 2020-02-29 16:50
Duplicate of #894 I believe.

**Closed by kelson42** 2020-02-29 16:50 UTC
