### ISSUE TITLE
wikipedia_es_basketball size smaller then older versions

### ISSUE THREAD

**Issue by MananJethwani** [openzim/mwoffliner#1356] opened 2021-01-01 11:59 UTC
seems like some images are not being downloaded which were being downloaded earlier
I found out that one such image - flag of egypt 1922-1952 orignally had a link
- ttps://upload.wikimedia.org/wikipedia/commons/thumb/`f/fb`/Flag_of_Egypt_%281922%E2%80%9319`52`%29.svg/30px-Flag_of_Egypt_%281922%E2%80%931952%29.svg.png
and when seen in zimfile it is -
ttps://upload.wikimedia.org/wikipedia/commons/thumb/`8/85`/Flag_of_Egypt_%281922%E2%80%9319`58`%29.svg/20px-Flag_of_Egypt_%281922%E2%80%931958%29.svg.png 

on further investigation I found out that response given by mobile version also had - ttps://upload.wikimedia.org/wikipedia/commons/thumb/`8/85`/Flag_of_Egypt_%281922%E2%80%9319`58`%29.svg/20px-Flag_of_Egypt_%281922%E2%80%931958%29.svg.png

**Comment by kelson42** [comment] 2021-01-01 12:02
@MananJethwani Do you have an example of artcle impacted?

**Comment by MananJethwani** [comment] 2021-01-01 12:25
@kelson42 -> Anexo:Baloncesto en los Juegos Mediterráneos de 1951

**Comment by kelson42** [comment] 2021-01-01 15:19
I start to believe that the problem is upstream and is a regression. The Parsoid seems under certain conditions to generate wrong images URLs.

If week look at the problem reported here in this ticket. We look at the article:
https://es.wikipedia.org/wiki/Anexo:Baloncesto_en_los_Juegos_Mediterr%C3%A1neos_de_1951

Which includes successfuly the image:
https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Egypt_%281922%E2%80%931952%29.svg/40px-Flag_of_Egypt_%281922%E2%80%931952%29.svg.png

But if we look to the Parsoid output:
https://es.wikipedia.org/api/rest_v1/page/html/Anexo:Baloncesto_en_los_Juegos_Mediterr%C3%A1neos_de_1951

I try to include and fail the image:
https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Egypt_%281922%E2%80%931958%29.svg/40px-Flag_of_Egypt_%281922%E2%80%931958%29.svg.png

... and the URL is wrong, it use the path `8/85/` but in fact `f/fb/`!

**Comment by kelson42** [comment] 2021-01-01 15:29
The problem is upstream and this is the old famous bug https://phabricator.wikimedia.org/T217540

**Comment by kelson42** [comment] 2021-01-01 15:30
Duplicate of https://github.com/openzim/mwoffliner/issues/1019

**Closed by kelson42** 2021-01-01 15:30 UTC
Labels: bug
