### ISSUE TITLE
wikipedia_en_all_mini is the same as _nopic

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1922] opened 2023-10-04 11:09 UTC
The last two iterations of https://farm.openzim.org/recipes/wikipedia_en_all_mini seem to be equivalent in size to the corresponding `nopic` zim files.

https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_mini_2023-09.zim 54G
https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_nopic_2023-09.zim 56G

Interestingly, this is not the case with, e.g. French
https://download.kiwix.org/zim/wikipedia/wikipedia_fr_all_mini_2023-09.zim 3.9G
https://download.kiwix.org/zim/wikipedia/wikipedia_fr_all_nopic_2023-09.zim 14G

but it is the case in German (and it happened after the August run)
https://download.kiwix.org/zim/wikipedia/wikipedia_de_all_mini_2023-08.zim 3.8G
https://download.kiwix.org/zim/wikipedia/wikipedia_de_all_mini_2023-09.zim 18G
https://download.kiwix.org/zim/wikipedia/wikipedia_de_all_nopic_2023-08.zim 17G

**Comment by kelson42** [comment] 2023-10-04 12:39
Duplicate of #1893

**Closed** 2023-10-04 12:39 UTC
Labels: bug
