### ISSUE TITLE
The inline javascript in recently-generated ZIM files can not be executed with a restrictive CSP

### ISSUE THREAD

**Issue by mossroy** [openzim/mwoffliner#324] opened 2018-04-12 12:37 UTC
In recent ZIM files, the sections of an article are collapsed when the screen is small.
If you click on the section name, it makes the content of this section visible.

It's a great feature, but it's currently implemented with some inline javascript, at least : 
- `<script>...</script>` tags
- `onclick` attributes with some javascript inside

In some contexts, the browser engines do not allow inline javascript, for security reasons. They block it through a https://en.wikipedia.org/wiki/Content_Security_Policy
It's the case in at least two contexts used by kiwix-js : Firefox OS apps (OK, I know this is dead), AND browser extensions (at least on Firefox and Chrome).

The consequence is that, on recent ZIM files, the sections remain invisible with kiwix-js. See https://github.com/kiwix/kiwix-js/issues/355
The first reason is that the javascript contents were not injected at all (but we're working on that). The second reason is that inline javascript is blocked (when inside the browser extension).

The proper way to solve this would be to replace the inline javascript code by some external javascript files (included in the ZIM file), that would add the event handlers on the section tags. It is the recommended way to comply with the CSP.

There is also a workaround (that needs to be tested), by adding a hash of each portion of inline code inside the manifest.json (file that declares the parameters of a browser extension). But it creates a dependency between the ZIM reader and the ZIM content, which is a problem. And I'm afraid we have a big amount of different inline javascript pieces of code, because it includes the contents of onclick attributes.

An even better way to solve this would be to not use javascript to toggle the sections, and use CSS3 selectors (I did not test, but it seems possible based on https://stackoverflow.com/questions/11023816/toggle-divs-without-using-javascript). It seems to be very widely supported : https://caniuse.com/#feat=css-sel3

**Comment by ISNIT0** [comment] 2018-04-12 12:44
Thanks for pointing this out!
The problem with the suggested fix is that various bits of MW content would need to be modified to add an input.

The existing fix was designed to be as non-invasive as possible.
What's the best way to replicate your issue? I'll try moving the code into another JS file.

**Comment by mossroy** [comment] 2018-04-12 19:56
Steps to reproduce : 
- install the kiwix-js browser extension, either on Firefox (https://addons.mozilla.org/firefox/addon/kiwix-offline/) or on Chromium/Chrome (https://chrome.google.com/webstore/detail/kiwix/donaljnlmapmngakoipdmehbfcioahhk)
- open the extension, and start the developer tools inside it (ctrl-shift-i), on the console tab
- inside kiwix-js, choose a recent ZIM file, and check for errors in the console
It currently displays errors regarding CSP, and thus ignores any inline javascript.

NB : please note that this version 2.2 of kiwix-js will not execute JS files anyway (we're working on it). But you should be able to check that the CSP errors are gone.

**Comment by mossroy** [comment] 2018-04-16 11:42
Another approach would be that the sections would be open by default (simply by changing or removing their CSS class inside the HTML), and some javascript code would close them when the page is loaded.
This way, a ZIM reader that does not support javascript would be able to display everything.

In kiwix-js, supporting javascript will not be easy. It raises several issues for us : 
- the CSP blocks inline javascript
- reading and decompressing this kind of text files is very slow in this implementation (we did not figure out why, for now)
- it might be difficult to implement it properly in jQuery mode

We will eventually work on all this, but it puts a some pressure, as the content is really not readable at all without javascript.

In general, I think it would be much better if the main content of the articles could be displayed without javascript. It seems to be done this way in online wikipedia : if I open any article of the mobile version of wikipedia, in a browser with https://noscript.net/ extension (which blocks javascript), I still can read the article content.

**Comment by mossroy** [comment] 2018-04-22 13:30
I understand it's probably not trivial to fix this issue. But it's a major problem for kiwix-js as recent zim files are currently unusable on it.
Please keep us in touch as soon as you decide how to deal with that.

**Comment by ISNIT0** [comment] 2018-04-22 14:04
Sorry, I've had much less time than I was expecting. Not sure when I'll be able to contribute.

**Comment by Jaifroid** [comment] 2018-04-25 11:42
No rush. I just want to note here that, when someone has time to look into a fix in mw-offliner, it appears the current script doesn't work properly for unhiding footnote/reference sections before jumping to the (foot)note in question. I think that part of the code is broken with current ZIMs. Not only can I not get it to work with standard "References", but there are several other types of "Notes" that appear with different IDs under different named sections that the script doesn't cater for. Some pages in WikiMed, for example, have both a "Notes" section and a "Refererences" section, with different note numbering styles. The script assumes only one kind of reference. It might be worth looking again at how Wikipedia's mobile style does this. As well as avoiding inline JavaScript banned by various CSPs, It would be ideal for us if there were a solution that doesn't require the injection of jQuery into the iframe.

As @mossroy says, we're looking at workarounds in short term.

**Comment by mossroy** [comment] 2018-05-23 20:56
We have implemented a workaround for that in kiwix-js : https://github.com/kiwix/kiwix-js/pull/358.
But that's not satisfying, as I explained in a previous comment.

IMHO, we should generate ZIM files that can be read (even in a basic way, without all features) by a browser without javascript enabled. And the content should completely work under a CSP that blocks inline javascript (like browser extensions).
If the inline javascript is ours (like the toggling sections of mwoffliner), it's certainly possible to move it in external files, even if I understand it's probably not straight-forward.
If some inline javascript comes from the original content (like in PhET and maybe some other ones), it might be more difficult, and involve some extra steps to do it.

But we don't have a choice if we want to support contexts under CSP (like browser extensions).
And I think it makes more sense to do that when we generate the ZIM file (because we know the structure of the original content, and do it once for all) than to do that in the readers (because we would have to do that in a generic way, which makes things much more complicated, and have to run that extra code on each article opening).

What's your opinion?

**Comment by ISNIT0** [comment] 2018-10-19 09:56
@mossroy What's the best way to test if this is fixed? I can build a partial ZIM file for you? How many pages do you need, which wiki?

**Comment by Jaifroid** [comment] 2018-10-19 10:32
@ISNIT0 Excellent! In that case, either a test Ray Charles ZIM (novid / mobile format) would be ideal, or the html/css/js of a typical page if you'd like us to look it over before you build a test ZIM.

**Comment by ISNIT0** [comment] 2018-10-19 11:18
I've had to make a few more changes in #415 to generate a new ZIM file. What is the best way to send the file to you?

**Comment by ISNIT0** [comment] 2018-10-27 15:20
Sorry for the delay - been away for a while.

Could you try this please: https://framadrop.org/r/e16cdXpSx8#An8mKs2cxsTudGZ1Vu1PjMU/8Rc8vALkffOP6JS0JNI=

**Comment by Jaifroid** [comment] 2018-10-29 07:16
Hi @ISNIT0 , thanks for the ZIM. When I run this in a version of Kiwix JS that supports JavaScript, I get a bunch of JS errors: "mw is not defined" and "mediaWiki is not defined". However, they are probably unrelated to this issue.

Can you give me a clue as to what I'm testing for? In the article in the archive you sent (`Climate of Colombia`) I don't see the caret arrow indicators as per screenshot below (from a WikiMed novid running in the same version of Kiwix JS), and clicking on the headings does nothing. If I knew the mechanism, I might be able to pinpoint whether the problem is at our end (Kiwix JS's support for JS in the ZIM is very preliminary in an experimental branch), or whether it's something else. Are you using JS or CSS, or a combination? In which files?

![image](https://user-images.githubusercontent.com/4304337/47634678-45ce2200-db4a-11e8-8c0d-f5a8ed3f2870.png)

**Comment by mossroy** [comment] 2018-10-29 09:38
@Jaifroid : the fix he made had 2 purposes (If I remember correctly) : 
- put a <noscript> tag, so that if there is no javascript support, the sections should be open (not sure if it would work in our context because javascript is not completely disabled)
- move the inline scripts in external JS files, so that section toggling should work even with restrictive CSP (like in browser extensions or with Firefox OS)

I should be able to test that during the week

**Comment by ISNIT0** [comment] 2018-10-29 09:46
Sorry, my mistake. That file was generated without `--mobileLayout`, please try this one instead:
https://framadrop.org/r/T5sVWDucVS#4kMqpRIlVmBlljv413dAdGDAZoSUSTG6mZZPJBrDEHk=

**Comment by Jaifroid** [comment] 2018-10-29 09:55
Ah, that's better! This one works correctly in our [JavaScript-enabled branch](https://github.com/kiwix/kiwix-js/tree/javaScript-support):

![image](https://user-images.githubusercontent.com/4304337/47642191-e7ac3980-db5f-11e8-93ae-c05eace89a71.png)

We need to test for the CSP issue specifically, because the JavaScript branch "intelligently" turns inline JS into attached scripts (but I don't see any such conversion happening with this ZIM's article).

Many thanks, @ISNIT0 , we'll get back to you later this week.

**Comment by Jaifroid** [comment] 2018-10-29 10:37
@ISNIT0 : slightly off-issue, but one thing I've noticed in this implementation is that if the References section is closed, the endnote reference markers don't work (endnote not jumped to or displayed). It works in online Wikipedia, mobile view with References section closed, though they use an overlay instead of jumping to the endnote.

**Comment by ISNIT0** [comment] 2018-10-29 10:56
@Jaifroid this seems to be a limitation when JavaScript is disabled, it's working on Kiwix Android for me.

**Comment by mossroy** [comment] 2018-10-29 15:16
I'm not 100% sure, but I think only half of the work has been done in this ZIM sample file.

The toggleOpenSection function has been correctly moved from the HTML page to a separate javascript file. But the calls to this function are still inline event handlers (HTML "onclick" attribute).
As explained above in https://github.com/openzim/mwoffliner/issues/324#issuecomment-380925738, these onclick inline scripts need to be replaced by programmatically adding event handlers.

That's why Firefox 62 still blocks these calls in a webextension, with a CSP error in the console like : 

> Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« script-src »). Source: onclick attribute on H2 element.

(sorry, my browser is configured in French)

In Chromium 69 as a webextension, however, the section toggling feature seemed to work fine when I quickly tested it. Maybe my test was wrong, because the spec https://developer.chrome.com/extensions/contentSecurityPolicy#JSExecution explicitly says inline event handlers are forbidden in extensions. It's also what people say in https://stackoverflow.com/questions/13591983/onclick-within-chrome-extension-not-working.

All tests have been done on branch `enable-javascript-inside-ZIM` (it enables javascript only in ServiceWorker mode), which I rebased on master.

**Comment by ISNIT0** [comment] 2018-10-30 17:02
Thanks @mossroy, I'll make this other change soon and post another ZIM

**Comment by mossroy** [comment] 2018-10-30 18:05
Cool, many thanks @ISNIT0 !

**Comment by ISNIT0** [comment] 2018-11-06 09:11
@mossroy Sorry it's taken so long!
Could you try this please:
https://framadrop.org/r/9OQckEwLus#2lrrE7QvF7Nu+K5OzWpFV9iKz2BNXLftY1eZTYUAnYw=

**Comment by Jaifroid** [comment] 2018-11-08 06:07
I confirm that on my JavaScript branch (which enables all JS in standard, non Service Worker mode) I'm getting similar errors in Edge. These errors are seemingly blocking the open-close functionality for me:

![image](https://user-images.githubusercontent.com/4304337/48180645-60f41b00-e31c-11e8-8e19-d3f47f6e2634.png)

**Comment by ISNIT0** [comment] 2018-11-08 07:18
The errors are actually nothing to do with this issue - they're from imported files from Parsoid.

Is this one any better for you? (sorry about the back and forth)
https://framadrop.org/r/OWWg2kYDOx#6VmInqztQQgyy2AGFxPH4a/lZT3zQ2SZvzz2Kl0GkZU=

**Comment by ISNIT0** [comment] 2018-11-08 07:29
@Jaifroid The problem seems to me that none of the JavaScript files actually define `mw`.

**Comment by Jaifroid** [comment] 2018-11-08 07:53
> js: JQMIGRATE: jQuery is not compatible with Quirks Mode
@mossroy JFYI I ran into this Quirks Mode issue when I created my branch for loading JS in jQuery mode. It seems to be caused by the fact that htmlArticle (the html we extract from the ZIM) contains a BOM. I have this comment in my code:
```
// Remove any BOM (causes Quirks Mode in browser)
        htmlArticle = htmlArticle.replace(/^[^<]*/, '');
```
It's a bit old now, but see http://malform.no/testing/html5/bom/index.html.utf8.html

**Comment by Jaifroid** [comment] 2018-11-08 07:59
@ISNIT0 For me, that new ZIM looks better. In @mossroy's JS branch for Service Worker mode, the code opens and closes headings correctly, and in master (which doesn't support JS), the headings are open by default.

It's not working in my branch, but I suspect that's my problem, not yours. However, give me some time to check it isn't a broader issue.

**Comment by Jaifroid** [comment] 2018-11-08 08:40
Actually, I've just realized, @mossroy , that if we remove our [workaround](https://github.com/kiwix/kiwix-js/blob/master/www/js/app.js#L960), then all headings are closed by default with this code (and there is no way to open them). So we would need to maintain the workaround, unless @ISNIT0 is willing to consider having headings open by default. I imagine that would break expected behaviour on the mobile apps?

![image](https://user-images.githubusercontent.com/4304337/48186952-79226500-e331-11e8-9019-2d00b7043674.png)

**Comment by Jaifroid** [comment] 2018-11-08 08:44
When I say "there is no way to open them", I mean in clients that don't support JS in the ZIM. @ISNIT0 , maybe one solution would be to have them open by default for such clients, and to close them programmatically in the `mobile.js` script. That way you get the expected behaviour in the Android/iOS apps, and still support clients that can't run JS from the ZIM.

**Comment by ISNIT0** [comment] 2018-11-08 09:02
There is some CSS that should force them to be open by default, but I'll take another look in a bit.

**Comment by ISNIT0** [comment] 2018-11-08 09:17
Okay, the CSS was broken from removing the inlined JS (we were using an attribute selector).
This should work:
https://framadrop.org/r/dJb6xo-S11#dwKgk9p0pk7YhAbR/dTh6Viw0eBLkS7MkFBv3bNrHBc=

**Comment by ISNIT0** [comment] 2018-11-09 10:18
@Jaifroid @mossroy Any news? 😄

**Comment by Jaifroid** [comment] 2018-11-09 10:34
I was just testing the latest one. The opening-closing JS works in @mossroy 's JS-enabled branch (in SW mode). On narrow screens all headings are closed by default. On a non-JS-enabled client, there is no way to open them, so we would need to continue to work around that in the client. I'd like to wait for @mossroy to have a look at the code, though, because he sees potential issues with extensions etc. that I'm unaware of.

**Comment by ISNIT0** [comment] 2018-11-09 11:43
I'm unable to reproduce the issue with the sections being closed on non-js clients.
When I disable JavaScript in Chrome, all the sections are open.

**Comment by Jaifroid** [comment] 2018-11-09 12:09
@ISNIT0 Reduce the width of your browser to a mobile-style size, and you should see all the sections are closed by this rule:

.collapsible-block {
    display: none;
}

@mossroy  To reproduce the issue in Kixix JS, we have to remove the workaround that opens all the closed sections.

**Comment by Jaifroid** [comment] 2018-11-09 12:11
PS @ISNIT0 The rule that opens the blocks when the screen width is greater than 720px is:
```
@media all and (min-width: 720px) {
    .client-js .collapsible-heading .indicator {
        display: none !important;
        /* this is to hide to "v" icone next to titles in desktop */
    }
}
```
These rules are in a file that is called something like "inserted style mobile.css".

**Comment by mossroy** [comment] 2018-11-11 10:39
In ServiceWorker mode, the latest ZIM works almost fine, and with less javascript errors. I tested it on Chromium (inside and outside an extension) : 

- the javascript code is properly externalized in mobile.js, and now works with the CSP of a browser extension. This was the main goal of this github issue : that's cool
- there are still a few javascript errors, but they do not seem related to this specific github issue. They are the same in kiwix-desktop : 
```
js: Uncaught SyntaxError: Unexpected token .
js: JQMIGRATE: jQuery is not compatible with Quirks Mode
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: module is not defined
js: Uncaught ReferenceError: module is not defined
```
- with a large screen, the sections are open by default, which I find a good behavior. Compared to previous versions, these sections can now be closed (and re-opened) when the user clicks on the title (it was not the case before). Why not but, in this case, the "v" icon next to titles should be visible IMHO
- with a small screen, the sections are closed by default, the "v" icon is visible and the toggling works. IMHO, it's exactly what is needed

In order to handle browser engines with no javascript support, @ISNIT0 added the following code in the HTML : 
```
  <noscript>
    <style>
      .collapsible-block {
        display: block !important;
      }
    </style>
  </noscript>
```
That's why his test with javascript disabled on Chrome works as expected. I think this should be kept.

However, this `noscript` tag is not interpreted by kiwix-js in jQuery mode, simply because javascript is not disabled by the browser engine. It is simply not injected by kiwix-js (in jQuery mode).
Until now, we worked around this issue by programmatically opening the sections in kiwix-js code (see the lines mentioned by @Jaifroid above). This workaround still works, but it's a dirty one, as we are doing some assumptions on the ZIM content (for example, it would stop working if the CSS styles are renamed). Maybe a better fix (in kiwix-js code) would be to remove the `<noscript>` and `</noscript>` tags in the HTML before injecting inside the iframe (and remove our current workaround). There are good chances it would work, and it would be a much cleaner workaround IMHO (more generic).

For @ISNIT0 understanding, @Jaifroid tries to implement in kiwix-js-windows the injection of javascript contents in jQuery mode (and it works on some ZIM files). This piece of code is not in upstream kiwix-js.

**Comment by ISNIT0** [comment] 2018-11-11 11:06
@mossroy I think there is nothing more you'd like me to do for this issue, is that correct?

**Comment by Jaifroid** [comment] 2018-11-11 11:16
@mossroy , which version of the ZIM did you test? The very latest that @ISNIT0 attached in [this post](https://github.com/openzim/mwoffliner/issues/324#issuecomment-436925816) (8th Nov 9.17am) does not seem to work as you describe. In Service Worker mode on Edge, with a wide screen, the sections beneath the headings remain closed by default, and they do not open when clicking them.

**Comment by Jaifroid** [comment] 2018-11-11 11:20
Forgot to say, that is in current master.

**Comment by mossroy** [comment] 2018-11-11 11:28
@Jaifroid : this is indeed the ZIM file I tested with, but you need to switch to the `enable-javascript-inside-ZIM` branch of kiwix-js (that enables javascript injection in ServiceWorker mode)
@ISNIT0 : I think so too, on this specific issue (unless @Jaifroid has another opinion). Regarding the behavior of sections on large screens, it's your call (but it's a different issue)

**Comment by Jaifroid** [comment] 2018-11-11 11:30
I'm happy for @ISNIT0 to go ahead. But I am curious as to why is the noscript block not being interpreted in Service Worker mode on our current master... So we're going to have to enable JavaScript or continue with workarounds in both jQuery and SW modes. But maybe that's for discussion elsewhere.

**Comment by Jaifroid** [comment] 2018-11-11 11:35
PS @ISNIT0 : I just wanted to say "many thanks" for your work on this!

**Comment by mossroy** [comment] 2018-11-11 12:58
@Jaifroid : The `noscript` tag is handled by the browser engine, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript : 

> The HTML <noscript> element defines a section of HTML to be inserted if a script type on the page is unsupported or if scripting is currently turned off in the browser.

In our case, the browser engine supports javascript, and is not disabled at browser level, so there's no reason for it to interpret the content of the `noscript` tag.

I created https://github.com/kiwix/kiwix-js/issues/433 to manually inject the `noscript` tag in jQuery mode, on kiwix-js. In ServiceWorker mode, merging the `enable-javascript-inside-ZIM` should be enough.

**Comment by Jaifroid** [comment] 2018-11-11 13:55
@mossroy OK, thanks for explaining, that makes sense now! I would have preferred a design in which all sections were open by default in the ZIM, and clients that support JavaScript in the ZIM would close them programmatically on loading the script, as this would work more universally, but I guess Kiwix JS is a special case.

**Comment by ISNIT0** [comment] 2018-11-11 14:57
I've merged #424 
Please let me know if you need anything else :)

**Comment by Jaifroid** [comment] 2018-11-14 09:06
@mossroy @ISNIT0 Here is a suggested solution:

Ship pages in the ZIM with the following style block in the head (NB, `!important` doesn't seem to be necessary if this is included in the html):
```
<style id="openAllSections">
    .client-js .collapsible-block {       
        display: block;
    }
</style>
```
Then include the following in `mobile.js`:
```
if (window.innerWidth < 720) {
    openSectionsStyleBlock = document.getElementById("openAllSections");
    openSectionsStyleBlock.sheet.deleteRule(0);
}
```
That JS would **replace** the current code:
```
if (window.innerWidth > 720) {
       $('.collapsible-heading').click();
}
```
I believe my suggested replacement achieves the following:

* Clients that cannot process JavaScript would display all sections as open in all views;
* Clients that can process JavaScript would close sections in mobile views

**Comment by Jaifroid** [comment] 2018-11-14 09:35
I think there's also a bug here:

`if (id === 0) return`

It should probably be:

`if (id === "0") return;`

This may be the root of the problem (I didn't test), because the bug probably allows clicking on the title heading. However, I still think my suggested solution is safer than the mass click, for the reasons stated above.

**Comment by ISNIT0** [comment] 2018-11-14 10:13
@Jaifroid I've implemented the above suggestion (`id === "0"`) rather than the larger change as I believe there are a lot of edge cases. I think we should re-visit this logic at some point, but for now I'd like to make the simplest changes possible.

**Comment by Jaifroid** [comment] 2018-11-14 10:17
@ISNIT0 It's your call, but the problem with the mass-click solution from our perspective is that it leaves us having to continue with workarounds in Kiwix JS... Yes, we can work around, but I do believe a more universal solution is possible...

Anyway, thanks for the fix. Did you test? Do you want us to test?

**Comment by ISNIT0** [comment] 2018-11-14 10:22
@Jaifroid I don't think you need to implement a work-around?

I've tested it locally, I'll post a zim file soon. I'm just fixing some other CSS issues.

**Comment by Jaifroid** [comment] 2018-11-14 10:51
@ISNIT0 Unfortunately we do need to continue with workarounds, because we are currently unable to process any **JavaScript inside ZIMs** in the jQuery mode of Kiwix JS. The result of running the new ZIM above **in our master branch with our current workaround removed** is what you see in the screenshot below. Why? Because the `noscript` section you included is completely ineffectual in Kiwix JS: our app is written in JavaScript, JS is turned on in the browser of course, _but the app cannot process **JS in the ZIM**_.

We have a branch that can process JS in the ZIM, but it only works with Service Workers, and Service Workers are not available in Firefox Extensions, in any browser running the app from the file system, and in several other use-cases (including the Microsoft Store) for Kiwix JS. In all these cases, we have to work around what you see in the screenshot below.

As you say, we can revisit the logic later if necessary. We have a workaround, it's OK, it's not a huge problem, but it is a bit ugly and non-generic....

I'm in the process of testing the new ZIM properly in different scenarios and will get back to you. So far, it's looking good in our JS-enabled branch.

![image](https://user-images.githubusercontent.com/4304337/48477687-2564bf80-e7fa-11e8-8cc9-b9988387488b.png)

**Comment by Jaifroid** [comment] 2018-11-14 11:55
@ISNIT0 I think there's a problem with this line in `mobile.js`:

`var ref = $('#References').closest('h2');`

The problem is that in English Wikimedia ZIMs there are some articles that have `id="Notes"` instead of `id="References"`, and some that even have both Notes and References sections, with different notes in each.

But the bigger problem is that the ID here varies according to different languages. For example, in a recent French WikiMed, the References section on most pages is called "Notes et références", and the ID closest to it is `id="Notes_et_r.C3.A9f.C3.A9rences"`. In a Spanish Wiktionary, the section is called "Referencias y notas", and the nearest ID is `id="Referencias_y_notas"`. Neither of these ZIMs contain pages with an ID of `References`, so the function would fail.

Since we can't programme in all the alternatives in hundreds of languages, we need a more generic solution. I have something in Kiwix JS Windows which finds the correct section using the footnote reference's `target.hash` as provided by the click object. It looks roughly like this (you add this event listener to each footnote reference marker):
```
reference.addEventListener("click", function (obj) {
    var refID = obj.target.hash || obj.target.parentNode.hash;
    if (!refID) return;
    refID = refID.replace(/#/, "");
    var refLocation = dcoument.getElementById(refID);
    var refNext = $('#refID').closest("H2");
    if (refNext) {
        refNext.classList.add("open-block");
        refNext = refNext.nextElementSibling;
        while (refNext && refNext.classList.contains("collapsible-block")) {
            refNext.classList.add("open-block");
            refNext = refNext.nextElementSibling;
        }
    }
});
```
Please note that's untested because in Kiwix JS Windows I did it without jQuery, which I'm not a fan of, so this bit: `$('#refID').closest("H2")` is something I'm unsure about. I have to admit that without jQuery it is rather more complicated, because you have to simulate a "closest" function, so I'm not bothering you with the details of that!

Sorry for this additional complication, but I've only just realized it.

**Comment by ISNIT0** [comment] 2018-11-14 22:09
@Jaifroid This seems like a separate issue, could you open it please?

Are you and @mossroy happy for this issue to be closed now?

**Comment by Jaifroid** [comment] 2018-11-15 08:44
@ISNIT0 According to my tests, it's all working now as intended (except for the #References issue mentioned above, but I agree that's a separate issue).

**Closed** 2018-11-15 08:46 UTC
Labels: bug, needs testing
