### ISSUE TITLE
no medicine.tsv for July 2024

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#2069] opened 2024-07-09 10:16 UTC
I  expected to find medicine.tsv for July 2024 in https://download.openzim.org/wp1/

but I don't see it.

**Comment by Jaifroid** [comment] 2024-08-03 07:34
I suppose we're looking at later in August for a new ZIM now? @tim-moody I could use your own versions if we upload them to download.kiwix.org in the correct folders (`/zim/other` for `mdwiki_en_all_maxi`, and `zim/.hidden/cutom_apps` for `mdwiki_en_all-app_maxi`). @kelson42 Might that be an acceptable workaround till this issue is fixed?

**Comment by tim-moody** [comment] 2024-08-03 08:03
As an update, we have engaged Ryan to modify the mirroring api so that mwoffliner can pull directly from mdwiki without needing the cacher and hope to have something to test in a week or so.

**Comment by tim-moody** [comment] 2024-08-03 08:19
In terms of using my ZIMs I would need to run again, as I was only testing if the process ran to completion with a full article list, but did not have the latest list for the month. Also, I did not build the app one.

I can do this if you like, but it will take perhaps two days to run.

**Comment by Jaifroid** [comment] 2024-08-03 08:31
@tim-moody It's probably best to focus on fixing the issue rather than putting time into running a non - farm version.  I don't suppose there have been critical article updates since June.

**Comment by tim-moody** [comment] 2024-08-03 08:34
@Jaifroid It's always successive approximation, article list every month, edits every week. If you can, I would use what you've got.

**Comment by Jaifroid** [comment] 2024-08-03 08:50
> If you can, I would use what you've got.

I don't currently have anything newer than the June ZIMs, but an app with those is already released, so no point doing a release just for the sake of a few code revisions/improvements since June.

**Comment by tim-moody** [comment] 2024-08-09 14:01
I notice in https://farm.openzim.org/recipes/mdwiki_app/config the image is

ghcr.io/openzim/mwoffliner:1.13.0 has not failed

So my question is why in https://farm.openzim.org/recipes/mdwiki/config can the image not be the same

I just ran the mdwiki recipe with 1.13.0 and it still succeeds. The attempts to modify the mdwiki api have not yet succeeded.



</body>
</html>[ghcr.io/openzim/mwoffliner:1.13.0](https://ghcr.io/openzim/mwoffliner)

**Comment by Jaifroid** [comment] 2024-08-10 19:16
Looking at the debug logs for [mdwiki](https://farm.openzim.org/pipeline/2cbd2ea9-d4d8-48ac-8d63-3e4f81ccce80/debug) (failed) and [mdwiki_app](https://farm.openzim.org/pipeline/25adb375-16d8-4429-be4e-ec5ae0113921/debug) (succeeded), the only difference I can see is that mdwiki has format `[ "novid:maxi", "" ]`, while mdwiki_app has format `[ "novid:maxi", "nodet,nopic:mini" ]`; `verbose` is set to true in mdwiki, and `withoutZimFullTextIndex` is set to true in mdwiki_app. Other than that the configurations are identical. There isn't much clue in the mdwiki log, because it just exited after 3 minutes in the pipeline, and most of that appears to be waiting to start.

I suppose the format `["novid:maxi", ""]` is valid (i.e. empty field for second option)? Otherwise, no clue.

**Comment by tim-moody** [comment] 2024-08-10 20:29
The important difference is that for mdwiki the command is

docker run -v /my-path:/output:rw --name mwoffliner_mdwiki --detach --cpu-shares 3072 --memory-swappiness 0 --memory 5368709120 **ghcr.io/openzim/mwoffliner:dev** mwoffliner --adminEmail="contact@kiwix.org" --articleList="https://mdwiki.wmcloud.org/nonwiki/lists/mdwikimed.tsv" --customMainPage="App/IntroPage" --customZimDescription="Healthcare articles curated by WikiProjectMed" --customZimFavicon="https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Wiki_Project_Med_Foundation_logo.svg/100px-Wiki_Project_Med_Foundation_logo.svg.png" --customZimTags="medical" --customZimTitle="MDWiki Medical Encyclopedia" --filenamePrefix="mdwiki_en_all" --format="novid:maxi" --format="" --mwUrl="https://mdwiki.wmcloud.org/" --optimisationCacheUrl="--------" --osTmpDir="/dev/shm" --outputDirectory="/output" --publisher="WikiProjectMed" --verbose --webp

while the command for running the app is

docker run -v /my-path:/output:rw --name mwoffliner_mdwiki_app --detach --cpu-shares 3072 --memory-swappiness 0 --memory 4294967296 **ghcr.io/openzim/mwoffliner:1.13.0** mwoffliner --adminEmail="contact@kiwix.org" --articleList="https://mdwiki.wmcloud.org/nonwiki/lists/mdwikimed.tsv" --customMainPage="App/IntroPage" --customZimDescription="Healthcare articles curated by WikiProjectMed" --customZimFavicon="https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Wiki_Project_Med_Foundation_logo.svg/100px-Wiki_Project_Med_Foundation_logo.svg.png" --customZimTags="medical" --customZimTitle="MDWiki Medical Encyclopedia" --filenamePrefix="mdwiki_en_all-app" --format="novid:maxi" --format="nodet,nopic:mini" --mwUrl="https://mdwiki.wmcloud.org/" --optimisationCacheUrl="--------" --osTmpDir="/dev/shm" --outputDirectory="/output" --publisher="WikiProjectMed" --webp --withoutZimFullTextIndex

They don't run the same version of mwoffliner.

**Comment by Jaifroid** [comment] 2024-08-11 05:04
Oh, I see -- I was looking at the configuration only. Thanks for noticing that difference @tim-moody.

I note the last scrape of mdwiki_app was on 13 June and it's paused. I believe most mwoffliner recipes have been paused due to using the new mobile HTML REST API which still has some formatting and image-size issues, though these are worse with dev than with 1.13.0. But sure, these should both be running the same version, and only 1.13.0 is currently usable with mdwiki, it seems.

As you know, I haven't been able to release a WikiMed app update since 16th June due to the lack of a new ZIM, so it would be great if @kelson42 or @benoit74 could:

1. Edit the [mdwiki recipe](https://farm.openzim.org/recipes/mdwiki/config) so it uses `mwoffliner:1.13.0` instead of `mwoffliner:dev`, and then
2. Relaunch both [mdwiki](https://farm.openzim.org/recipes/mdwiki) and [mdwiki_app](https://farm.openzim.org/recipes/mdwiki_app) manually.

Let's see if that does the trick for now.

**Comment by kelson42** [comment] 2024-08-13 19:35
This ticket original problem is a duplicate of https://github.com/openzim/wp1_selection_tools/issues/48. To clarify the situation I will close it, other problems can be treated at other places.

**Closed by kelson42** 2024-08-13 19:35 UTC
