### ISSUE TITLE
Factrio Wiki Unable to Hack Startup Module error

### ISSUE THREAD

**Issue by jontyms** [openzim/mwoffliner#1595] opened 2022-02-27 17:40 UTC
command used `docker run -v zims:/data openzim/mwoffliner  mwoffliner --mwUrl https://wiki.factorio.com/ --outputDirectory /data/ --adminEmail  email@example.com --mwApiPath  /api.php --mwWikiPath / --mwModulePath  /load.php --articleList /data/articles --verbose --speed 5`

getting this error 
```
Failed to run mwoffliner after [24s]: {
        "stack": "Error: unable to hack startup module\n    at hackStartUpModule (/tmp/mwoffliner/lib/util/dump.js:124:23)\n    at Object.<anonymous> (/tmp/mwoffliner/lib/util/dump.js:141:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/util/dump.js:24:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "message": "unable to hack startup module"
}

```

Thanks for your help!
I'm probably doing something wrong

**Comment by kelson42** [comment] 2022-06-26 15:38
@jontyms Thank you for your bug report. This tivket is a duplicate of #1409

**Closed by kelson42** 2022-06-26 15:38 UTC
Labels: bug, duplicate
