### ISSUE TITLE
Kochwiki returns "unable to hack startup module"

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1462] opened 2021-05-12 16:34 UTC
See last two runs : https://farm.openzim.org/recipes/kochwiki

**Comment by MananJethwani** [comment] 2021-05-13 10:13
duplicate of #1409

**Closed** 2021-05-13 10:34 UTC
Labels: bug, duplicate

**Comment by jescala** [comment] 2021-09-20 05:02
I'm getting this error as well. Any suggestions on how to fix it?

`
[log] [2021-09-20T04:51:19.409Z] Downloading module dependencies
Failed to run mwoffliner after [7088s]: {
	"stack": "Error: unable to hack startup module\n    at hackStartUpModule (/tmp/mwoffliner/lib/util/dump.js:126:23)\n    at Object.<anonymous> (/tmp/mwoffliner/lib/util/dump.js:143:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/util/dump.js:24:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
	"message": "unable to hack startup module"
}


**********

unable to hack startup module

**********


[log] [2021-09-20T04:51:19.593Z] Exiting with code [2]
`
