### ISSUE TITLE
getArticlesByNS is not finding all articles on EN Wikipedia

### ISSUE THREAD

**Issue by ISNIT0** [openzim/mwoffliner#993] opened 2019-09-30 13:30 UTC
EN Wikipedia scrapes are finding about half of the existing articles.

**Comment by ISNIT0** [comment] 2019-09-30 13:35
The log that happens here https://github.com/openzim/mwoffliner/blob/master/src/util/mw-api.ts#L97
Adds up to the 2.5M number and there is no error - There must be something in our continuation logic that's not working properly.

**Comment by kelson42** [comment] 2019-11-13 15:41
This has failed again in last attempt.

Here's the correct task: [5dad76a6efd26e8d5d6a6c75](https://farm.openzim.org/tasks/5dad76a6efd26e8d5d6a6c75). Started Oct 21, finished Oct 26th.

Full Log: https://logs.warehouse.farm.openzim.org/mwoffliner_5dad76a6efd26e8d5d6a6c75.log.xz

End of log:

```
T:392883; Set article indexes
set index
T:392884; Resolve mimetype
T:392886; create title index
T:392901; 7611238 title index created
T:392901; 40756 clusters created
T:392901; fill header
T:392905; write zimfile :
T:392905;  write header
T:392905;  write mimetype list
T:392905;  write url prt list
T:392908;  write title index
T:392911;  write directory entries
T:392924;  write cluster offset list
T:392924;  write cluster data
T:392929; 1000/40756
T:392934; 2000/40756
T:392940; 3000/40756
T:392945; 4000/40756
T:392949; 5000/40756
T:392954; 6000/40756
T:392963; 7000/40756
T:392970; 8000/40756
T:392982; 9000/40756
T:392990; 10000/40756
T:392997; 11000/40756
T:393003; 12000/40756
T:393013; 13000/40756
T:393022; 14000/40756
T:393030; 15000/40756
T:393037; 16000/40756
T:393045; 17000/40756
T:393055; 18000/40756
T:393062; 19000/40756
T:393070; 20000/40756
T:393077; 21000/40756
T:393088; 22000/40756
T:393096; 23000/40756
T:393103; 24000/40756
T:393110; 25000/40756
T:393119; 26000/40756
T:393129; 27000/40756
T:393136; 28000/40756
T:393144; 29000/40756
T:393177; 30000/40756
T:393190; 31000/40756
T:393198; 32000/40756
T:393208; 33000/40756
T:393217; 34000/40756
T:393225; 35000/40756
T:393233; 36000/40756
T:393241; 37000/40756
T:393249; 38000/40756
T:393260; 39000/40756
T:393267; 40000/40756
T:393411;  write checksum
T:393411; finish
[log] [2019-10-26T02:24:42.842Z] Summary of scrape actions: {
	"files": {
		"success": 207982,
		"fail": 1281
	},
	"articles": {
		"success": 3083055,
		"fail": 3428
	},
	"redirects": {
		"written": 4324589
	}
}
[log] [2019-10-26T02:24:42.843Z] Finished dump
[log] [2019-10-26T02:24:42.843Z] Closing HTTP agents...
[log] [2019-10-26T02:24:42.843Z] All dumping(s) finished with success.
[log] [2019-10-26T02:24:42.848Z] Flushing Redis DBs
Finished running mwoffliner after [407480s]
[log] [2019-10-26T02:24:42.851Z] Exiting with code [0]
[log] [2019-10-26T02:24:42.851Z] Deleting temporary directory [/tmp/mwoffliner-1571649206894]
```

First reported in https://github.com/openzim/zim-requests/issues/207

**Comment by kelson42** [comment] 2019-11-13 15:44
Here is the piece of log which is interesting

```
[log] [2019-10-21T13:07:30.689Z] Got [169] articles from namespace [0]
[log] [2019-10-21T13:07:31.571Z] Got [208] articles from namespace [0]
[log] [2019-10-21T13:07:32.305Z] Got [221] articles from namespace [0]
[log] [2019-10-21T13:07:33.082Z] Got [192] articles from namespace [0]
[log] [2019-10-21T13:07:33.822Z] Got [240] articles from namespace [0]
[log] [2019-10-21T13:07:34.506Z] Got [179] articles from namespace [0]
[log] [2019-10-21T13:07:35.018Z] Got [156] articles from namespace [0]
[log] [2019-10-21T13:07:36.010Z] Got [154] articles from namespace [0]
[log] [2019-10-21T13:07:36.562Z] Got [0] articles from namespace [0]
[log] [2019-10-21T13:07:36.567Z] Doing dump
[log] [2019-10-21T13:07:36.568Z] Writing zim to [/output/wikipedia_en_all_nopic_2019-10.zim]
[log] [2019-10-21T13:07:36.568Z] Flushing Redis file store
[log] [2019-10-21T13:07:37.588Z] Found [3] stylesheets to download
[log] [2019-10-21T13:07:37.588Z] Downloading stylesheets and populating media queue
[log] [2019-10-21T13:07:37.802Z] Downloaded stylesheets
[log] [2019-10-21T13:07:37.803Z] Saving favicon.png...
[log] [2019-10-21T13:07:37.902Z] Getting Main Page
[log] [2019-10-21T13:07:37.902Z] Create main page redirection from [index] to[A/User%3AThe%20other%20Kiwix%20guy%2FLanding]
[log] [2019-10-21T13:07:37.991Z] Getting articles
[log] [2019-10-21T13:07:37.997Z] Heartbeat - OK
[log] [2019-10-21T13:07:37.999Z] Worker [0] Processing batch of article ids [["1980_in_Ireland","+11 more +","Ginn_Open"]]
[log] [2019-10-21T13:07:38.001Z] Worker [1] Processing batch of article ids [["John_W._Preston","+8 more +","History_of_Inter_Milan"]]
```

Looks like it just get 0 articles to retrieve at a time it should not

**Comment by kelson42** [comment] 2019-12-12 15:38
Made two runs on my local machine, and all the article ids have been retrieved properly so for now... it is absolutely unclear if the problem comes from there (I will built in more debug) or from somewhere else.

**Comment by rgaudin** [comment] 2019-12-23 14:47
FYI a successful run occurred on the zimfarm and got all the articles.
So we know it's not systematic nor worker related. Doesn't provide much help for identifying the root cause but we can at least rule-out a zimfarm/WMF worker specific issue.

**Comment by kelson42** [comment] 2020-02-29 16:57
I think here what we need for the moment is at the end of getting all article titles from namespaces, to know the total number of them (stored in Redis).

**Comment by kelson42** [comment] 2020-04-18 13:34
@bakshiutkarsha The problem does not occur anymore AFAIK. The reason is probably that the conditions that such a sporadic issue occurs are not there anymore because I don't have seen an obvious fix for that bug been implemented. Therefore, I suspect that the bug might still be there, but without a clear reprocase and because the bug does not occur on Zimfarm, it is at the same time hard and not so valuable to try to find the root cause. So if you see something obvious, please fix it, otherwise I would be happy if you just make what I have proposed in the previous comment: I want to get printed how many article titles/medata are stored in the Redis before MWoffliner starts to retrieve the HTML. To me, this is what needs to be done to close this ticket now. That way if the problems occurs again, I will be able to identify if the problem occurs at the time we retrieve the medata or later in the process.

**Closed** 2020-04-25 09:00 UTC
Labels: bug
