### ISSUE TITLE
Articles consist of a single word. wiktionary ru

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1218] opened 2020-07-19 13:53 UTC
**wiktionary_ru_all_maxi_2020-04.zim**
Article**s** consist of a single word:
![wiktionary_ru_all_maxi_2020-04](https://user-images.githubusercontent.com/65112331/87876318-16c3a800-c9e0-11ea-9a83-00727cd0908c.gif)

And here is how the [**тезаурус**](https://ru.wiktionary.org/wiki/тезаурус) article should look.

**Comment by kelson42** [comment] 2020-07-19 13:58
Duplicate of #1177

**Closed by kelson42** 2020-07-19 13:58 UTC
