### ISSUE TITLE
Unable to use mwoffliner to download private wiki

### ISSUE THREAD

**Issue by jadestorm** [openzim/mwoffliner#1267] opened 2020-09-29 19:37 UTC
Hi folk, we have a pretty stock mediawiki install, but we have locked it down so that it requires a login to access any data.  We also have it running at the root level of it's domain instead of /wiki/.  With that said -- I'm getting (with obvious replacements):

```
$ docker run -ti openzim/mwoffliner:1.10.12 mwoffliner --mwUrl=https://our.wiki.domain.edu  --adminEmail=MYEMAIL --mwWikiPath=/ --mwApiPath=api.php --mwModulePath=load.php --mwUsername=MYUSERNAME --mwPassword=MYPASSWORD --verbose
starting redis-server in the background…
[log] [2020-09-29T19:14:45.961Z] Starting mwoffliner v1.10.12...
[log] [2020-09-29T19:14:45.967Z] Getting text direction...
[log] [2020-09-29T19:14:45.968Z] Getting site info...
[log] [2020-09-29T19:14:45.968Z] Getting sub-title...
[info] [2020-09-29T19:14:45.977Z] Downloading [https://our.wiki.domain.edu/]
[info] [2020-09-29T19:14:45.978Z] Getting JSON from [https://our.wiki.domain.edu/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc]
[info] [2020-09-29T19:14:45.978Z] Downloading [https://our.wiki.domain.edu/]
(node:12) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[error] [2020-09-29T19:14:46.176Z] FATAL - Failed to get MediaWiki Metadata
Failed to run mwoffliner after [1s]: {
        "stack": "TypeError: Cannot read property 'general' of undefined\n    at MediaWiki.<anonymous> (/tmp/mwoffliner/lib/MediaWiki.js:212:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/MediaWiki.js:24:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "message": "Cannot read property 'general' of undefined"
}


**********

Cannot read property 'general' of undefined

**********
```

I went to the url it used for the JSON query and got:

```
{"batchcomplete":"","warnings":{"siteinfo":{"*":"Unrecognized values for parameter \"siprop\": category, wikidesc."}},"query":{"general":{"mainpage":"Main Page","base":"https://our.wiki.domain.edu/index.php/Main_Page","sitename":"Information Technology","logo":"https://our.wiki.domain.edu/images/ourlogo-2x2-red-min.png","generator":"MediaWiki 1.31.8","phpversion":"7.2.32","phpsapi":"apache2handler","dbtype":"mysql","dbversion":"5.7.28-31-57-log","imagewhitelistenabled":"","langconversion":"","titleconversion":"","linkprefixcharset":"","linkprefix":"","linktrail":"/^([a-z]+)(.*)$/sD","legaltitlechars":" %!\"$&'()*,\\-.\\/0-9:;=?@A-Z\\\\^_`a-z~\\x80-\\xFF+","invalidusernamechars":"@:","fixarabicunicode":"","fixmalayalamunicode":"","case":"first-letter","lang":"en","fallback":[],"fallback8bitEncoding":"windows-1252","writeapi":"","maxarticlesize":2097152,"timezone":"UTC","timeoffset":0,"articlepath":"/index.php/$1","scriptpath":"","script":"/index.php","variantarticlepath":false,"server":"https://our.wiki.domain.edu","servername":"our.wiki.domain.edu","wikiid":"mediawiki_it","time":"2020-09-29T19:09:01Z","uploadsenabled":"","maxuploadsize":104857600,"minuploadchunksize":1024,"galleryoptions":{"imagesPerRow":0,"imageWidth":120,"imageHeight":120,"captionLength":"","showBytes":"","showDimensions":"","mode":"traditional"},"thumblimits":[120,150,180,200,250,300],"imagelimits":[{"width":320,"height":240},{"width":640,"height":480},{"width":800,"height":600},{"width":1024,"height":768},{"width":1280,"height":1024}],"favicon":"https://our.wiki.domain.edu/favicon.ico","centralidlookupprovider":"local","allcentralidlookupproviders":["local"],"interwikimagic":"","magiclinks":[],"categorycollation":"uppercase"},"namespaces":{"-2":{"id":-2,"case":"first-letter","canonical":"Media","*":"Media"},"-1":{"id":-1,"case":"first-letter","canonical":"Special","*":"Special"},"0":{"id":0,"case":"first-letter","content":"","*":""},"1":{"id":1,"case":"first-letter","subpages":"","canonical":"Talk","*":"Talk"},"2":{"id":2,"case":"first-letter","subpages":"","canonical":"User","*":"User"},"3":{"id":3,"case":"first-letter","subpages":"","canonical":"User talk","*":"User talk"},"4":{"id":4,"case":"first-letter","subpages":"","canonical":"Project","*":"OURIT"},"5":{"id":5,"case":"first-letter","subpages":"","canonical":"Project talk","*":"CHASSIT talk"},"6":{"id":6,"case":"first-letter","canonical":"File","*":"File"},"7":{"id":7,"case":"first-letter","subpages":"","canonical":"File talk","*":"File talk"},"8":{"id":8,"case":"first-letter","subpages":"","canonical":"MediaWiki","*":"MediaWiki"},"9":{"id":9,"case":"first-letter","subpages":"","canonical":"MediaWiki talk","*":"MediaWiki talk"},"10":{"id":10,"case":"first-letter","subpages":"","canonical":"Template","*":"Template"},"11":{"id":11,"case":"first-letter","subpages":"","canonical":"Template talk","*":"Template talk"},"12":{"id":12,"case":"first-letter","subpages":"","canonical":"Help","*":"Help"},"13":{"id":13,"case":"first-letter","subpages":"","canonical":"Help talk","*":"Help talk"},"14":{"id":14,"case":"first-letter","canonical":"Category","*":"Category"},"15":{"id":15,"case":"first-letter","subpages":"","canonical":"Category talk","*":"Category talk"}},"statistics":{"pages":154,"articles":22,"edits":2191,"images":2,"users":11,"activeusers":1,"admins":4,"jobs":0},"variables":["!","currentmonth","currentmonth1","currentmonthname","currentmonthnamegen","currentmonthabbrev","currentday","currentday2","currentdayname","currentyear","currenttime","currenthour","localmonth","localmonth1","localmonthname","localmonthnamegen","localmonthabbrev","localday","localday2","localdayname","localyear","localtime","localhour","numberofarticles","numberoffiles","numberofedits","articlepath","pageid","sitename","server","servername","scriptpath","stylepath","pagename","pagenamee","fullpagename","fullpagenamee","namespace","namespacee","namespacenumber","currentweek","currentdow","localweek","localdow","revisionid","revisionday","revisionday2","revisionmonth","revisionmonth1","revisionyear","revisiontimestamp","revisionuser","revisionsize","subpagename","subpagenamee","talkspace","talkspacee","subjectspace","subjectspacee","talkpagename","talkpagenamee","subjectpagename","subjectpagenamee","numberofusers","numberofactiveusers","numberofpages","currentversion","rootpagename","rootpagenamee","basepagename","basepagenamee","currenttimestamp","localtimestamp","directionmark","contentlanguage","pagelanguage","numberofadmins","cascadingsources"]}}
```

Any thoughts on what I'm missing here?  =)  Thanks!

**Comment by kelson42** [comment] 2020-09-30 08:16
@jadestorm Thank you for your bug report. We have in general many problem to scrape Mediawikis with a configuration which tends to be strongly different from the Wikimedia wikis. Not on purpose, but fixing all the bugs is currently much for our small resources. If your wiki is private, I strongly suspect that the problem is #42. There is as well #758.

**Comment by jadestorm** [comment] 2020-09-30 14:59
Ack yeah we are running the latest LTS version (1.31?) so definitely beyond the 1.28.

Unfortunately I don't have the time to dive into it myself either so --- I'm going to look for another solution.  I leave it up to you if you want to keep the report open or not.  =)  I certainly don't mind testing fixes in the future if some come!

**Comment by kelson42** [comment] 2020-10-08 07:48
Duplicate of #42.

**Closed** 2020-10-08 07:48 UTC
Labels: bug, duplicate, question
