### ISSUE TITLE
[REGRESSION] Article subsections on new zim files from mwoffliner 1.8.1 cannot be opened

### ISSUE THREAD

**Issue by pyroshroom** [openzim/mwoffliner#633] opened 2019-03-24 20:33 UTC
The article subsections cannot be expanded in the latest zim files from https://download.kiwix.org/zim/ (I assume they were produced on mwoffliner 1.8.1 as they were created after March 17, 2019). I have tested the zim files on both the Windows Kiwix 0.9 and Android Kiwix 2.4 and the issue is present in both.

The zim files I've found to be affected are: wiktionary_en_simple_all_novid_2019-03.zim, westeros_en_all_novid_2019-03.zim, artofproblemsolving_en_all_novid_2019-03.zim and rationalwiki_en_all_novid_2019-03.zim 

This is not an issue on wikipedia_en_simple_all_nopic_2019-03.zim, from March 19, 2019 where the subsections can be expanded (or are already expanded on windows).

**Comment by kelson42** [comment] 2019-03-25 06:09
@pyroshroom Thx for your bug report, we need to check that quickly. Please use Kiwix-Desktop 2.0 (even in beta) instead of deprecated Kiwix-xulrunner 0.9. See https://download.kiwix.org/release/kiwix-desktop/

**Comment by pyroshroom** [comment] 2019-03-25 07:06
Tested the same files again with Kiwix Desktop 2.0 beta4, still cannot expand the article subsections on the previously mentioned files ( wiktionary_en_all_novid_2019-03.zim, westeros_en_all_novid_2019-03.zim, artofproblemsolving_en_all_novid_2019-03.zim and rationalwiki_en_all_novid_2019-03.zim ) along with westeros_en_all_nopic_2019-03.zim not working.

However, wiktionary_en_simple_all_nopic_2019-03 and wikipedia_en_simple_all_nopic_2019-03.zim are working properly with expandable subsections.

**Comment by cm8** [comment] 2019-03-25 19:03
I've had the same problem with the test case I have been working on.

`~/node_modules/.bin/mwoffliner --mwUrl=https://de.wikibooks.org --redis=redis://127.0.0.1:6379 --adminEmail=foo@bar.net --verbose --withoutZimFullTextIndex --addNamespaces=102,4,14 --articleList list`

with the only entry in `list` being
`Blender_Dokumentation/_Tutorials/_Partikel/_Gras`

The problem is that a `site.js` script may overwrite window.onload handler, so the one that is supposed to be installed from `mwoffliner/res/script.js` will never run.

My solution to the problem:
* previous hacks were removed because startUp() is not present anymore in recent mediawiki instances, see [T39894](https://phabricator.wikimedia.org/T39894)
* still applying previous hacks leads to script errors in the browser, i.e. breaks recent startup.js code
* however, if mwoffliner is run against old mediawiki instances it may still be needed (not tested here)

```diff
--- node_modules/mwoffliner/src/util/dump.ts.orig	1985-10-26 09:15:00.000000000 +0100
+++ node_modules/mwoffliner/src/util/dump.ts	2019-03-25 19:42:17.043976350 +0100
@@ -155,24 +155,8 @@
     // return :
     //   a promise resolving 1 if data has been succesfully saved or resolving 0 if data was already in redis
 
-    // the 2 variable functions below are a hack to call startUp() (from module startup) when the 3 generic dependencies (startup, jquery, mediawiki) are loaded.
-    // on wikipedia, startUp() is called in the callback of the call to load.php to dl jquery and mediawiki but since load.php cannot be called in offline,
-    // this hack calls startUp() when custom event fireStartUp is received. Which is dispatched when module mediawiki has finished loading
-    function hackStartUpModule(jsCode: string) {
-        return jsCode.replace(
-            'script=document.createElement(\'script\');',
-            `
-                    document.body.addEventListener('fireStartUp', function () { startUp() }, false);
-                    return;
-                    script=document.createElement('script');`,
-        );
-    }
-    function hackMediaWikiModule(jsCode: string) {
-        jsCode += `(function () {
-            const startUpEvent = new CustomEvent('fireStartUp');
-            document.body.dispatchEvent(startUpEvent);
-        })()`;
-        return jsCode;
+    function hackSiteModule(jsCode: string) {
+        return jsCode.replace(/aOnloadFunctions *= *new *Array\(\);/, 'aOnloadFunctions = window.onload ? [ window.onload ] : [ ];');
     }
 
     let moduleUri: string;
@@ -194,10 +178,9 @@
             if (redisResult === 1) {
                 const { content } = await downloader.downloadContent(moduleApiUrl);
                 let text = content.toString();
-                if (module === 'startup' && type === 'js') {
-                    text = hackStartUpModule(text);
-                } else if (module === 'mediawiki' && type === 'js') {
-                    text = hackMediaWikiModule(text);
+                if (module === 'site' && type === 'js') {
+                    text = hackSiteModule(text);
+		    logger.info(`Hacked Site Module: ${text}`);
                 }
 
                 try {
```

-------
There were other issues, unrelated to the one being discussed here I've fixed along the way:
```diff
--- node_modules/mwoffliner/src/Dump.ts.orig	1985-10-26 09:15:00.000000000 +0100
+++ node_modules/mwoffliner/src/Dump.ts	2019-03-25 19:17:36.089820887 +0100
@@ -155,7 +155,7 @@
             if (typeof str === 'undefined') {
                 return undefined;
             }
-            return escape ? encodeURIComponent(str) : str;
+            return escape ? encodeURIComponent(str).replace(/%2F/g, '/') : str;
         }
         return e(filename) + (this.nozim ? '.html' : '');
     }
--- node_modules/mwoffliner/src/util/saveArticles.ts.orig	1985-10-26 09:15:00.000000000 +0100
+++ node_modules/mwoffliner/src/util/saveArticles.ts	2019-03-25 19:15:22.911745285 +0100
@@ -182,8 +182,6 @@
         // For video, we get multiple SOURCE tages with different resolutions
 
         const posterUrl = videoEl.getAttribute('poster');
-        const videoPosterUrl = getFullUrl(webUrlHost, posterUrl);
-        const newVideoPosterUrl = getMediaBase(videoPosterUrl, true);
         let videoSources: any[] = Array.from(videoEl.children).filter((child: any) => child.tagName === 'SOURCE');
 
         // Firefox is not able to display correctly <video> nodes with a height < 40.
@@ -200,13 +198,16 @@
             return;
         }
 
-        if (posterUrl) { videoEl.setAttribute('poster', newVideoPosterUrl); }
-        videoEl.removeAttribute('resource');
-
-        if (!srcCache.hasOwnProperty(videoPosterUrl)) {
-            srcCache[videoPosterUrl] = true;
-            mediaDependencies.push(videoPosterUrl);
+        if (posterUrl) {
+            const videoPosterUrl = getFullUrl(webUrlHost, posterUrl);
+            const newVideoPosterUrl = getMediaBase(videoPosterUrl, true);
+            videoEl.setAttribute('poster', newVideoPosterUrl);
+            if (!srcCache.hasOwnProperty(videoPosterUrl)) {
+                srcCache[videoPosterUrl] = true;
+                mediaDependencies.push(videoPosterUrl);
+            }
         }
+        videoEl.removeAttribute('resource');
 
         function byWidthXHeight(a: DominoElement, b: DominoElement) {
             // If there is no width/height, it counts as zero, probably best?
```

**Comment by cm8** [comment] 2019-03-25 19:10
An alternative may be to use `onloadend` event handler to register the function in `mwoffliner/res/script.js` that is to be installed on window load event.

After all, `site.js`  may look different for each mediawiki instance and the logic in the patch above may not catch each and every way the window.onload handler may be overwritten by `site.js` variants.

But since I was unsure about the compatibility of `onloadend` events in recent browser engines, I've taken the route to patch `site.js` nonetheless.

**Comment by cm8** [comment] 2019-03-25 22:35
Here's a smaller change tested to work that is independent of changing `site.js` and thus should be compatible to more wikimedia instances.

```diff
--- node_modules/mwoffliner/res/script.js.orig	1985-10-26 09:15:00.000000000 +0100
+++ node_modules/mwoffliner/res/script.js	2019-03-25 23:24:58.487329422 +0100
@@ -9,7 +9,7 @@
     $('#mf-section-' + id).toggleClass('open-block').prev().toggleClass('open-block')
 }
 
-window.onload = function () {
+function registerOpenSectionHandlers() {
     $('.mw-ref').on({
         click: function (ev) {
             var targetId = ev.target.hash || ev.target.parentNode.hash;
@@ -33,3 +33,5 @@
         $('.collapsible-heading').click();
     }
 }
+
+document.addEventListener("DOMContentLoaded", registerOpenSectionHandlers);
```
Please still consider removing or updating the startUp() related hacks `mwoffliner/src/util/dump.ts` for the reasons given above.

**Comment by kelson42** [comment] 2019-03-26 08:27
@ISNIT0 Can you please ASAP have a look to that and do the necessary if we really have a bug in PROD?

**Comment by kelson42** [comment] 2019-03-30 10:26
@ISNIT0 I confirm a problem, hopefuly the same as reported first. Take for example this ZIM file https://download.kiwix.org/zim/wiktionary/wiktionary_en_simple_all_novid_2019-03.zim. Open it with `kiwix-serve` or `kiwix-desktop. Go to article `Gary`. The paragraph "Proper noun" is empty (collapsed?). If you go online, you see the definition https://simple.wiktionary.org/wiki/Gary.

**Comment by ISNIT0** [comment] 2019-03-30 10:28
@kelson42 Yes, I've found some examples. I'm doing a local scrape myself now

**Comment by ISNIT0** [comment] 2019-03-30 10:33
The problem seems to be that JQuery is not required by the MW instance, so our queries which rely on JQuery don't work. I'll add a static JQuery to all ZIM files if it's not found (JQuery is used by our other injected scripts too)

**Comment by kelson42** [comment] 2019-03-30 10:34
@ISNIT0 I hardly believe that jquery is not a dependence of Mediawiki!

**Comment by ISNIT0** [comment] 2019-03-30 17:44
I've scraped simple wiktionary completely locally (with pictures) to both ZIM and raw files. My above idea about JQuery was incorrect, but I'm unable to see issues with the picture version.
Re-scraping now without pictures to see if there is a difference between my scrape and what's on download.kiwix.org

**Comment by ISNIT0** [comment] 2019-03-30 22:05
After doing my own scrape, I've noticed differences:
My local scrape:
![image](https://user-images.githubusercontent.com/5173131/55282220-2aa54f80-5340-11e9-8075-7842d6485fde.png)

![image](https://user-images.githubusercontent.com/5173131/55282224-4a3c7800-5340-11e9-9e79-790a4635056b.png)

**Comment by kelson42** [comment] 2019-03-31 05:40
@ISNIT0 Please stick to the example given in the bug report. Here the article `Gary`. Otherwise you just make the whole analysis more complex. The invisible content is in the HTML, you can see:
```
<h2 class="section-heading in-block collapsible-heading" tabindex="0" aria-haspopup="true" aria-controls="content-collapsible-block-1" data-section-id="1">
    <div class="mw-ui-icon mw-ui-icon-arrow mw-ui-icon-element indicator" title=""></div>
    <span class="mw-headline" id="Proper_noun">Proper noun</span>
</h2>
<div id="mf-section-1" class="mf-section-1 collapsible-block" aria-pressed="true" aria-expanded="true">
    
<span>
</span><table border="0" width="100%">
<tbody><tr>
<td bgcolor="#e2e2ff" valign="top" width="49%">
<p>Proper noun<br>
<b><a href="Gary" title="Gary">Gary</a></b></p></td></tr>

</tbody></table><span>
</span><span>
</span>
<ol><li><b>Gary</b> is a <a href="male" title="male">male</a> <a href="given_name" title="given name">given name</a>.</li></ol>


    
</div>
```

It is just invisible!

**Comment by ISNIT0** [comment] 2019-03-31 09:31
My local scrape (using master) does show content: 
![image](https://user-images.githubusercontent.com/5173131/55287388-7f7cb080-53a8-11e9-9bf3-c3d6e13be511.png)

**Comment by kelson42** [comment] 2019-03-31 10:10
@ISNIT0 OK, and what is the difference between your local ZIM and https://download.kiwix.org/zim/wiktionary/wiktionary_en_simple_all_novid_2019-03.zim ? That should be easy to see I guess. Then we need you to understand why you scraping with 1.8.1 and zimfarm scraping with 1.8.1 generate two different results.

**Comment by ISNIT0** [comment] 2019-04-02 17:46
@kelson42 To summarise from our conversation earlier:
The bug is not present when scraping with 1.8.1 with an article list containing just `Gary`. I've scraped the wiki completely with master, and want to scrape on the same machine with `1.8.1` before trying to diagnose the issue.

**Comment by ISNIT0** [comment] 2019-04-03 14:01
Just did a full scrape with 1.8.1 on my vps:
```
npm i -g mwoffliner@1.8.1
mwoffliner --mwUrl=https://simple.wiktionary.org --verbose --redis=redis://127.0.0.1:6379 --format=nopic --adminEmail=admin@kiwix.com > run-simple-nopic-1.8.1.log 2>&1
```
The generated zim file has a working `Gary` page:
https://framadrop.org/r/mHqO6MH1mj#kJbbrBGcmzb319kSFVzw3AH08peQzSTGd1RApA62NeU=

**Comment by kelson42** [comment] 2019-04-03 14:08
@ISNIT0 OK, I'm not particuliary surprised. The comment I made 3 days ago is more valid than even I guess https://github.com/openzim/mwoffliner/issues/633#issuecomment-478328495

**Comment by cm8** [comment] 2019-04-03 14:20
I'd start by extracting `site.js`, `startup.js`, `mediawiki.js` and `script.js` (last one from mwoffliner/res/, the other downloaded when building) from both ZIM files and then compare those.

If the content of the section is in the html, you'll probably find that the non-working ZIM file (from download.kiwix.org) exhibits the problem I've referred to in the lengthy comment above, quote:

> The problem is that a site.js script may overwrite the window.onload handler that is installed by mwoffliner/res/script.js.  The onload handlers from site.js will run, but the one from script.js that are responsible to install the onclick handlers for the section headings will not.

Maybe site.js on wikitionary (an online file after all) has changed in the meantime, so you won't get the same constellation within the ZIM file as the zimfarm-built version got.

**Comment by ISNIT0** [comment] 2019-04-03 15:20
Looks like the the simple wiktionary `novid` has only 4 script files, which is much less than the expected number (10-15).
```
> ls -lart wiktionary_simple_novid_remote/-/j%2fjs_modules%2f*
-rw-r--r--  1 user  staff    574  3 Apr 17:07 wiktionary_simple_novid_remote/-/j%2fjs_modules%2farticle_list_home.js
-rw-r--r--  1 user  staff   6398  3 Apr 17:07 wiktionary_simple_novid_remote/-/j%2fjs_modules%2fimages_loaded.min.js
-rw-r--r--  1 user  staff   1765  3 Apr 17:07 wiktionary_simple_novid_remote/-/j%2fjs_modules%2fjsConfigVars.js
-rw-r--r--  1 user  staff  24103  3 Apr 17:07 wiktionary_simple_novid_remote/-/j%2fjs_modules%2fmasonry.min.js
-rw-r--r--  1 user  staff   1085  3 Apr 17:07 wiktionary_simple_novid_remote/-/j%2fjs_modules%2fscript.js
```


I suppose for some reason the js downloads failed on the scrape. I'm not sure why, without the logs. This also explains why I can't reproduce it.

Odd that the normal and `nopic` versions work fine

On a separate note, there seem to be `26584` duplicate entries for `j/js_modules/jsConfigVars.js`

**Comment by ISNIT0** [comment] 2019-04-03 16:07
We can't be sure if this is fixed or not. I haven't been able to reproduce this, and I've been scraping this wiktionary a lot...

**Comment by Jaifroid** [comment] 2019-04-05 15:14
@ISNIT0, as I mentioned in another thread, it would make more sense if we defaulted to all sections open, and then close them with JavaScript/CSS when the page finishes loading, then at least you'd have a sensible fallback in situations like this. If anything in the dependency fails, all sections would still be open and can be read in all clients. The current logic is to start with everything closed, and then to use jQuery to click every header on desktop screen sizes to open them. It would make more sense the other way round. I suggested some code here: https://github.com/openzim/mwoffliner/issues/324#issuecomment-438588931.

**Comment by kelson42** [comment] 2019-04-09 06:29
@automactic Could you give us a list of ZIM file on download.kiwix.org wihch have been generated with 1.8.2? I have checked https://download.kiwix.org/zim/wikipedia/wikipedia_hr_all_novid_2019-04.zim which has been made yesterday and the problem is still there! The whole situation start to be critical.

**Comment by kelson42** [comment] 2019-04-09 06:30
@automactic Can you give a way to @ISNIT0 to access the log of all the scraping jobs?

**Comment by ISNIT0** [comment] 2019-04-09 06:33
@kelson42 Which article? I'm not seeing the issue

**Comment by kelson42** [comment] 2019-04-09 06:38
@ISNIT0 Check "Ivan Balović" for example. But all articles are impacted, I hardly see how you can not see it!!!

**Comment by ISNIT0** [comment] 2019-04-09 06:40
Okay, I see it. Though I guess I found a bug related to opening files in Kiwix Mac... (Opening a ZIM file from outside the app opens the previous zim)

**Comment by ISNIT0** [comment] 2019-04-09 06:45
Seems like the same cause, only 5 JS files.
Those logs would be really helpful

**Comment by ISNIT0** [comment] 2019-04-09 11:08
I've adjusted the JS downloading logic to stop all scraping if the modules can't be downloaded. This should surface the error more easily (and stop us publishing dud ZIM files)

Change will be in a PR soon

**Comment by cm8** [comment] 2019-04-10 15:35
This should all be a lot safer and more "offline" if the suggestion made by Jaifroid was followed.  Scripts are a mess, especially if mwoffliner does not control them all:  It seems to be very unsafe to mix a fixed set of scripts with custom ones downloaded from some wiki to be mirrored.

So in any case, having a failsafe/fallback mechanism like the one that has been proposed by Jaifroid should prevent future "disasters" and make mwoffliner compatible with a broader range of wikis out there.

**Comment by ISNIT0** [comment] 2019-04-10 16:46
Bare in mind that we got to where we are after a lot of back and forth:
https://github.com/openzim/mwoffliner/issues/324

If anyone would like to propose a change, please make sure it respects everything that was discussed here :)

**Comment by cm8** [comment] 2019-04-11 21:08
> Bare in mind that we got to where we are after a lot of back and forth:
> #324
> 
> If anyone would like to propose a change, please make sure it respects everything that was discussed here :)

ok, but why don't you judge a solution by "works/ doesn't work" rather than by "it respects anything discussed" - the later seems bound to fail sooner or later or maybe sooner, I guess, but maybe I'm wrong.

**Comment by ISNIT0** [comment] 2019-04-12 08:13
@cm8 I haven't passed judgement of anything 😄  "works" is a term that means different things to different people, as the mentioned ticket shows.
If the behaviour is changed, it's possible those same questions will come up and we'll end up with an infinite loop of regressions 👍

**Comment by cm8** [comment] 2019-04-12 16:56
In face of the symptoms shown (unaccessible items and basically broken files), your general answer to a very specific problem is rather unacceptable.  "works" is a term that is defined by "does what is advertised/claimed":

The claim is to snapshot wiki content for offline use.  If the result is merely showing section headlines, then, among people with a rest of sanity, the terms work/doesn't work are not negotiable.  Of course, people are free to fork a copy to maintain a _working_ version, but this just adds to overall maintenance burden.

**Comment by mossroy** [comment] 2019-04-12 18:21
Let's calm down...
While I also think having the sections open by default would be safer, implementation decisions are always a compromise between many factors, not a simple working/non-working choice.

**Comment by ISNIT0** [comment] 2019-05-01 17:55
Closed by https://github.com/openzim/mwoffliner/pull/708

**Closed by ISNIT0** 2019-05-01 17:55 UTC
Labels: bug
