### ISSUE TITLE
Title is not shown since 2023-11-max

### ISSUE THREAD

**Issue by zkosk** [openzim/mwoffliner#1982] opened 2024-02-02 00:30 UTC
![image](https://github.com/openzim/mwoffliner/assets/76477726/d52ee511-2083-4bf1-a321-1f31900d5463)

**Comment by zkosk** [comment] 2024-02-02 00:33
2023-10-maxi is OK. 2023-11-maxi and 2024-1-maxi have this problem.

**Comment by zkosk** [comment] 2024-02-02 00:37
2023-10-maxi is OK. 2023-11-maxi and 2024-1-maxi have this problem.

**Comment by Jaifroid** [comment] 2024-02-05 17:35
Thanks for reporting this! This issue is a duplicate of #1872, and is reportedly fixed by #1886.

**Closed by Jaifroid** 2024-02-05 17:35 UTC
Labels: duplicate
