### ISSUE TITLE
Missing article in Wikipedia in English

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1555] opened 2021-11-20 20:01 UTC
ZIM: 2021-03 English Wikipedia + 2021-11 English Wikipedia (mini)

- http://library.kiwix.org/wikipedia_en_all_maxi/A/Christianization_of_the_late_Roman_empire
- http://library.kiwix.org/wikipedia_en_all_mini/A/Christianization_of_the_late_Roman_empire
- https://en.wikipedia.org/wiki/Christianization_of_the_late_Roman_empire

Missing article:

- ![Screenshot_20211120-204455_Samsung Internet](https://user-images.githubusercontent.com/71934042/142739415-cc063469-7343-4e35-84db-f059f71817f1.jpg)

2021-03:

- ![2021-03](https://user-images.githubusercontent.com/71934042/142739385-18e67633-8c28-419a-a5a3-0fea9f555f15.jpg)

2021-11:

- ![Screenshot_20211120-204339_Samsung Internet](https://user-images.githubusercontent.com/71934042/142739398-73088bb5-dd59-48e2-b427-404e2bd50652.jpg)

**Comment by Jaifroid** [comment] 2021-11-21 08:29
I confirm that this is also missing in `wikipedia_en_all_maxi_2021-02.zim`, so it seems to be systemic. Below are the only ones I can find with a liberal search. There is "Christianization of the Roman Empire" but not "Christianization of the late Roman Empire". I wonder if this has to do with the article not having many (any?) links to it. I can't find it in any of the templates associated with it, but I haven't searched extensively.

![image](https://user-images.githubusercontent.com/4304337/142755047-e7333be2-ebe0-44ed-839f-e2e7abc0e62d.png)

**Comment by Jaifroid** [comment] 2021-11-21 08:32
Possibly if you created a "See also: ..." link to this article from "Christianization of the Roman Empire" (in live Wikipedia), then MWOffliner would (eventually) pick it up.

**Comment by Inbefortus** [comment] 2021-11-21 09:18
> I wonder if this has to do with the article not having many (any?) links to it. I can't find it in any of the templates associated with it, but I haven't searched extensively.

@Jaifroid One can not find the article anywhere else, only here
https://en.wikipedia.org/wiki/Religion_in_ancient_Rome#Transition_to_Christian_hegemony

- ![20211121_100817](https://user-images.githubusercontent.com/71934042/142756245-c75a4efe-36f2-4b42-96a9-e52ef614ffcb.jpg)

Thanks to full-text-search on Kiwix iOS, I can confirm that this article 100% does not exist. Interestingly odd.

**Comment by kelson42** [comment] 2021-11-21 09:32
Strange indeed. The article is quite big. I guess some kind of problem with Wikimedia backend. I will check.

**Comment by Inbefortus** [comment] 2021-11-24 12:09
@kelson42 @Jaifroid Surprisingly, this article exists in 2021-11 English Wikipedia (no pic), but is not faithful to the original:

- http://library.kiwix.org/wikipedia_en_all_nopic/A/Christianization_of_the_late_Roman_empire

- 2021-11 (no pic)
![Screenshot_20211124-120727_Samsung Internet](https://user-images.githubusercontent.com/71934042/143230794-3f181513-6e14-4b9a-b8da-d05323bf0135.jpg)

This part of the article is missing:

- Original
![Screenshot_20211124-124157_Samsung Internet](https://user-images.githubusercontent.com/71934042/143233252-5df84149-6cb3-4581-ad85-8a2e4cf0c090.jpg)

Such as:

- Original
![20211124_125453](https://user-images.githubusercontent.com/71934042/143233753-d74d0b9e-db99-4d6e-a423-1f3d34dc1378.jpg)

- 2021-11 (no pic)
![Screenshot_20211124-124511_Samsung Internet](https://user-images.githubusercontent.com/71934042/143233793-833697d4-240a-4430-8402-adb2401ffd9f.jpg)

- Original
![20211124_130530](https://user-images.githubusercontent.com/71934042/143235166-8a3101c2-672c-4195-bfd6-9b24c82b12d9.jpg)

- 2021-11 (no pic)
![Screenshot_20211124-130702_Samsung Internet](https://user-images.githubusercontent.com/71934042/143235312-905c1a89-305c-44c2-8c4b-9d0d50dc9f5c.jpg)

**Comment by Inbefortus** [comment] 2021-11-24 12:32
This article has been edited countless times as you can see here https://en.wikipedia.org/w/index.php?title=Christianization_of_the_late_Roman_empire&offset=&limit=500&action=history

MWOffliner happened to scrape a "bad" revision while it was being edited so many times. This is the revision that was scraped:

- https://en.wikipedia.org/w/index.php?title=Christianization_of_the_late_Roman_empire&oldid=1056009796

But why this particular article wasn't scraped before is still a mystery.

**Comment by Jaifroid** [comment] 2021-11-24 16:02
@Inbefortus On another issue, @kelson42 informed me about this Parsoid bug:

https://phabricator.wikimedia.org/T226931 

This means that the scraped version we get is often not the very latest at the time of scraping, and MWOffliner doesn't scrape a consistent Wikimedia version number (which it really needs to do to ensure consistency given the long amount of time needed to complete a scrape). This could explain what you're seeing.

**Comment by kelson42** [comment] 2022-06-21 20:47
@Jaifroid @Inbefortus I wonder if we should close thisnticket because the article is there now and if still wrong version then coukd be considered as duplicate of #1397 ?

**Comment by Inbefortus** [comment] 2022-06-21 21:27
@kelson42 I would say, yes, this ticket should be closed, at least with respect to this particular article. The article is fine in the current English Wikipedia. But there is definitely something going on with articles being renamed/moved during scraping. Maybe we should create a new ticket for that in the future?

**Comment by kelson42** [comment] 2022-06-26 10:13
@Jaifroid The number of links pointing to an article plays no role if an article is scraped or not. An article is scraped either because this is given in the —articleList or because it is part of a namespace to be scraped. Both been « decided » at the very beginning of the scrape process.

@Inbefortus If an article is moved during the scrape, then the old name is part of article title list to scrape and the new name is not. MWoffliner will attempt to scrape with the old title and won’t with the new title. If the move operation has been made without a redirect, then for sure the article won’t be scraped and links to old name will be broken and links to new name will be removed (in the zim). If the move operation has left a redirect, then the attempt to scrape the old title shoukd generate a redirect wntry (old name) and scrape the article with the new title (To be verified) ; and links to old title will work and links to new titles will be removed.

@Inbefortus Would you be able to check this behaviour?

**Comment by Inbefortus** [comment] 2022-06-26 11:57
> If the move operation has left a redirect, then the attempt to scrape the old title should generate a redirect entry (old name) and scrape the article with the new title (To be verified) ; and links to old title will work and links to new titles will be removed.

@kelson42 If I comprehend this appropriately, you're not wrong(?):

The search for `Argument from inconsistent revelations` leads to `Religious pluralism` since May 1, which happened during scraping.

![20220626_130108](https://user-images.githubusercontent.com/71934042/175811614-d4278ea4-c26f-4f34-885a-f7a7b5978525.jpg)


https://user-images.githubusercontent.com/71934042/175812295-6494dec9-cec7-45e7-b311-495d92a4872b.mp4



The article before the move:

![Screenshot_20220626-124931_Samsung Internet](https://user-images.githubusercontent.com/71934042/175811695-375b0992-4117-4a72-ab9a-2027d12de1fd.jpg)

**Comment by kelson42** [comment] 2022-06-26 15:32
@Inbefortus Great! Good catch! So closing this ticket.

**Closed by kelson42** 2022-06-26 15:32 UTC
Labels: question, wikimedia
