### ISSUE TITLE
The Contents table at the top of each Wikipedia article

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1382] opened 2021-01-21 14:07 UTC
At the top of each Wikipedia article there is a small table of **Contents**.
And in Kiwix there is no small table of **Contents**.
However, I noticed that earlier in Kiwix there was such a table of **Contents**. Here is a **[picture for an example](https://commons.wikimedia.org/wiki/File:Emmabuntus-2-12.04-Kiwix-en.png)**:
![Emmabuntus-2-12 04-Kiwix-en](https://user-images.githubusercontent.com/65112331/105361689-9dad4380-5c02-11eb-9da9-bb47458a79c3.gif)

If possible, please return the table of **Contents**. After all, this sign (**Contents**) is very helpful in navigating through the article.

**Comment by kelson42** [comment] 2021-01-21 14:12
Duplicate of #596

**Closed by kelson42** 2021-01-21 14:12 UTC

**Comment by archenemies** [comment] 2021-02-13 08:10
What does this have to do with JavaScript? I use a JavaScript-less text browser to view Kiwix and Wiktionary, and I too have noticed the same issue: the Kiwix version lacks a table of contents.

Sometimes the table of contents is really necessary...

**Comment by kelson42** [comment] 2021-02-13 08:13
There is no plan for the moment to provide a TOC for js-less browsers.

**Comment by archenemies** [comment] 2021-02-13 09:14
@kelson42 That's interesting, why is Kiwix using JavaScript, when Wiktionary shows the contents in HTML?

**Comment by kelson42** [comment] 2021-02-13 09:54
First of all wikipedia does not always show the TOC AFAIK (on mobile?) then we have the Kiwix apps which want a better control over the content (like the TOC in a non HTML fashion).

**Comment by archenemies** [comment] 2021-02-13 10:34
Thanks. I guess I'll submit a feature request to put that back.
