### ISSUE TITLE
Illustration metadata stored as text

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#2016] opened 2024-04-16 09:56 UTC
Tested with a couple ZIMs ;

The `Illustration_48x48@1` metadata is a PNG image that is stored on the ZIM but the entry's `mimetype` is set to `text/plain` which is wrong, incorrect regarding the spec and thus preventing tools that read metadata from working as expected.

**Comment by kelson42** [comment] 2024-05-07 19:40
Actually a duplicate of #1974

**Closed** 2024-05-07 19:40 UTC
Labels: bug, duplicate, good first issue
