### ISSUE TITLE
Wrongly formatted element in zim file

### ISSUE THREAD

**Issue by leanhdung1994** [openzim/mwoffliner#1451] opened 2021-04-30 19:56 UTC
I'm using `wiktionary_en_all_maxi_2021-03.zim` . It seems there is an error with entry `-ation` .
![image](https://user-images.githubusercontent.com/28704090/116747879-d8dbc180-a9fe-11eb-9269-db0d4305ffb2.png)

**Comment by kelson42** [comment] 2021-05-01 05:04
Duplicate of #1360

**Closed by kelson42** 2021-05-01 05:04 UTC
