### ISSUE TITLE
Incomplete scrapping of widgets in gbf.wiki

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1011] opened 2019-10-29 07:07 UTC
The Granblue wiki's landing page is largely incomplete and shows random code where widgets are added. See:
* http://library.kiwix.org/granbluefantasy_en_all_nopic_2018-10/A/Main_Page.html

<s>Additionaly the address seems odd with a double "all" (e.g. "all_all_nopic")</s> I confirm. Fixed.

**Comment by kelson42** [comment] 2020-12-05 23:14
Latest version looks not to bad http://library.kiwix.org/granbluefantasy_en_all_maxi/A/Main_Page but we still have uninterpreted HTML!

**Comment by kelson42** [comment] 2021-01-07 21:43
The last problem left is a duplicate of #1360

**Closed by kelson42** 2021-01-07 21:43 UTC
Labels: bug
