### ISSUE TITLE
Native build fail while setting up.

### ISSUE THREAD

**Issue by LakmaNeha** [openzim/mwoffliner#1036] opened 2020-03-02 18:24 UTC
Here's the log

System OS - Mac
Node version - tried 8, 10, 11.

> 0 info it worked if it ends with ok
1 verbose cli [ '/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/node',
1 verbose cli   '/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:native' ]
2 info using npm@6.4.1
3 info using node@v11.0.0
4 verbose run-script [ 'prebuild:native', 'build:native', 'postbuild:native' ]
5 info lifecycle @openzim/libzim@2.1.0~prebuild:native: @openzim/libzim@2.1.0
6 info lifecycle @openzim/libzim@2.1.0~build:native: @openzim/libzim@2.1.0
7 verbose lifecycle @openzim/libzim@2.1.0~build:native: unsafe-perm in lifecycle true
8 verbose lifecycle @openzim/libzim@2.1.0~build:native: PATH: /Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim/node_modules/.bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/.bin:/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim/node_modules/.bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/.bin:/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin:/Users/srikarchowdavarapu/.rvm/gems/ruby-2.6.3/bin:/Users/srikarchowdavarapu/.rvm/gems/ruby-2.6.3@global/bin:/Users/srikarchowdavarapu/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/srikarchowdavarapu/.rvm/bin
9 verbose lifecycle @openzim/libzim@2.1.0~build:native: CWD: /Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim
10 silly lifecycle @openzim/libzim@2.1.0~build:native: Args: [ '-c',
10 silly lifecycle   'autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist' ]
11 silly lifecycle @openzim/libzim@2.1.0~build:native: Returned: code: 1  signal: null
12 info lifecycle @openzim/libzim@2.1.0~build:native: Failed to exec build:native script
13 verbose stack Error: @openzim/libzim@2.1.0 build:native: `autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @openzim/libzim@2.1.0
15 verbose cwd /Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim
16 verbose Darwin 18.7.0
17 verbose argv "/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/node" "/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/npm" "run" "build:native"
18 verbose node v11.0.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @openzim/libzim@2.1.0 build:native: `autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist`
22 error Exit status 1
23 error Failed at the @openzim/libzim@2.1.0 build:native script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

As these doesn't seem to work, I have also tried with nodejs 12. As found in this thread https://github.com/charto/nbind/issues/133 I tried forking `node-libzim` and used  `mceSystems/nbind` instead of `charto/nbind`, even that doesn't seem to work. Please let me know if there is anything else I can do to setup this in my local. Thanks.

**Comment by kelson42** [comment] 2020-03-02 18:47
To run MWoffliner on macOS, you need to compile the libzim and node-libzim yourself. I recommend to just you a Linux in a Virtualbox or a Docker container.

**Comment by kelson42** [comment] 2020-03-02 18:51
Basically a duplicate of https://github.com/openzim/node-libzim/issues/32

**Closed** 2020-04-07 17:06 UTC
Labels: question
