### ISSUE TITLE
No internal links available on June en.wikinews zim

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#839] opened 2019-06-24 05:43 UTC
http://download.kiwix.org/zim/wikinews/wikinews_en_all_novid_2019-06.zim
also has some images missing and gives this

![Screenshot_20190621-081823_Kiwix](https://user-images.githubusercontent.com/21675885/59994302-9fdca400-9653-11e9-8c52-69db400fa1e2.jpg)

**Comment by ISNIT0** [comment] 2019-06-25 10:48
Unfortunately I can't reproduce this...

I'm only part way through a local scrape, but internal links seem to be working fine. We'll see about images later

**Comment by ISNIT0** [comment] 2019-06-25 14:31
![image](https://user-images.githubusercontent.com/5173131/60107145-53ca5600-975e-11e9-9683-7fb382ed8f57.png)
All seems to be okay when I run it locally...

**Comment by kelson42** [comment] 2019-07-03 16:04
Duplicate of #858

**Closed by kelson42** 2019-07-03 16:04 UTC
Labels: bug
