### ISSUE TITLE
psiram - zim

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1216] opened 2020-07-16 10:42 UTC
Incorrect display **psiram_ru_all_maxi_2020-05.zim** (141 Kb).
I think it's just an empty file since it weighs so little (141 Kb).

**Kiwix 2.0.1-1** (*.appimage):
![Psiram 2020-05-12](https://user-images.githubusercontent.com/65112331/87661312-1372b700-c769-11ea-8f3a-716579e93ac2.png)

**FireFox 2.8.0** (extension):
![Psiram 2020-05-WebExtenFireFox](https://user-images.githubusercontent.com/65112331/87661742-cfcc7d00-c769-11ea-97df-e0e70440dcde.png)

**Comment by kelson42** [comment] 2020-07-19 13:53
The problem is that the API of psiram is broken. I complained about that but the problem is still there. Unfortunately MWoffliner was not dying properly so unproper ZIM files have been created and older (proper) ones removed. I has been reported and fixed with #1035. I have deactivated the psiram rulesom zimfarm and removed all psiram "empty" files.

**Closed by kelson42** 2020-07-19 13:53 UTC
