### ISSUE TITLE
Vikidia scraper repeatedly crashes + last run missed most articles

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1061] opened 2020-03-24 14:02 UTC
The last available version for Vikidia_fr_all_maxi (as well as fr_nopic_maxi) has Mars as a landing page (see http://library.kiwix.org/vikidia_fr_all_maxi_2019-12) and missed quite a few articles (248 instead of 29,000+).

The last few runs on the zim farm all failed (https://farm.openzim.org/recipes/vikidia_fr). It is not the case with the other languages but they are all notably smaller.

**Comment by kelson42** [comment] 2020-05-01 12:54
This is a duplicate of #660

**Closed by kelson42** 2020-05-01 12:54 UTC
Labels: bug
