### ISSUE TITLE
getCategories: Cannot read property 'missing' of null

### ISSUE THREAD

**Issue by TheNetStriker** [openzim/mwoffliner#1281] opened 2020-10-20 09:06 UTC
I've got the following error when running mwoffliner with the --getCategories option on my private wiki. (Version 1.35.0)

```
Failed to run mwoffliner after [29s]: {
	"stack": "TypeError: Cannot read property 'missing' of null\n    at Object.<anonymous> (/tmp/mwoffliner/lib/util/categories.js:88:42)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/util/categories.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
	"message": "Cannot read property 'missing' of null"
}
**********
Cannot read property 'missing' of null
**********
```

I found out that the [Category:Pages_with_syntax_highlighting_errors](https://www.mediawiki.org/wiki/Category:Pages_with_syntax_highlighting_errors) was causing this problem. As soon as I fixed all the pages in this category the error was fixed. Can you explain this and can you implement a fix that this will not happen anymore?

**Comment by kelson42** [comment] 2020-10-23 13:56
@TheNetStriker Thank you for your bug report. Unfortunately many things are not working fine with categories :(. Closing as duplicate of https://github.com/openzim/mwoffliner/issues/829

**Closed by kelson42** 2020-10-23 13:56 UTC
