### ISSUE TITLE
vikidia_en_all_2015-11 has external links

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1] opened 2016-02-22 15:28 UTC
http://download.kiwix.org/portable/vikidia/kiwix-0.9+vikidia_en_all_2015-11.zip

has a number of links back to en.vikidia.org, mostly js and a css:

Uncaught SyntaxError: Unexpected end of input
head.js:17821  No <meta name="ResourceLoaderDynamicStyles"> found, inserting dynamically
https://download.vikidia.org/en.vikidia.org/extensions/VisualEditor/lib/ve/src/ve.track.js Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://download.vikidia.org/en.vikidia.org/skins/Vector/collapsibleTabs.js Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://download.vikidia.org/en.vikidia.org/extensions/VisualEditor/lib/ve/src/ve.js Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://download.vikidia.org/en.vikidia.org/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.init.js Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://download.vikidia.org/en.vikidia.org/extensions/VisualEditor/modules/ve-mw/init/styles/ve.init.mw.ViewPageTarget.init.css Failed to load resource: the server responded with a status of 503 (Service Unavailable)
https://en.vikidia.org/w/resources/src/jquery/jquery.byteLength.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/lib/jquery.client/jquery.client.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/jquery/jquery.mwExtension.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/jquery/jquery.accessKeyLabel.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/jquery/jquery.tabIndex.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/lib/jquery/jquery.ba-throttle-debounce.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/mediawiki/mediawiki.notify.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/mediawiki/mediawiki.util.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/mediawiki/mediawiki.Title.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/mediawiki/mediawiki.Uri.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/mediawiki.legacy/wikibits.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/mediawiki.legacy/ajax.js Failed to load resource: net::ERR_CONNECTION_REFUSED
https://en.vikidia.org/w/resources/src/mediawiki.page/mediawiki.page.startup.js Failed to load resource: net::ERR_CONNECTION_REFUSED
vector.js:8 Uncaught TypeError: $(...).lastTabIndex is not a function
https://download.vikidia.org/en.vikidia.org/extensions/VisualEditor/modules/ve-mw/init/styles/ve.init.mw.ViewPageTarget.init.css Failed to load resource: the server responded with a status of 503 (Service Unavailable)

**Comment by kelson42** [comment] 2016-03-09 20:31
Yes, I confirm the bug. The problem is that the dumping script is globally weak to retrieve the javascript dependencies. Hopefully this will be fixed in June, during the hackathon - if not earlier.

**Comment by kelson42** [comment] 2017-05-12 12:27
@tim-moody  How does that looks like to you with last Vikidia ZIM?

**Comment by tim-moody** [comment] 2017-05-12 13:19
Testing is blocked by kiwix-tools #30

**Comment by kelson42** [comment] 2017-05-12 15:29
https://github.com/kiwix/kiwix-tools/issues/30 is about library.xml and search feautre. Nothing to do with that bug. Why not jsut running kiwix-serve vikidia.zim ?

**Comment by tim-moody** [comment] 2017-05-13 17:59
I do not see any of the above messages in the console of FF 53 or Chrome 58 for 

http://download.kiwix.org/portable/vikidia/kiwix-0.9+vikidia_en_all_2017-04.zip

**Comment by kelson42** [comment] 2017-05-13 18:53
@tim-moody That is a really good news! Thank for confirming the bug is fixed!

**Closed by kelson42** 2017-05-13 18:53 UTC
