### ISSUE TITLE
Fix wikibook_fr top menu links

### ISSUE THREAD

**Issue by letompouce** [openzim/mwoffliner#1660] opened 2022-09-19 08:45 UTC
The [latest wikibooks_fr_all_maxi](https://library.kiwix.org/wikibooks_fr_all_maxi_2022-08/A/Accueil) top menu has no links (Arths, Loisirs, Histoire, etc).

**Comment by kelson42** [comment] 2022-09-19 08:53
@letompouce Duplicate of https://github.com/openzim/mwoffliner/issues/1661 ?

**Comment by letompouce** [comment] 2022-09-19 08:57
This issue is about wikibooks (with a S, sorry, may we edit the issue title?) ZIMs, and the other one is about Wikiversity ZIMs.

They may have the same root cause, sorry if I was noisy ^^'

**Comment by kelson42** [comment] 2022-09-19 09:00
@letompouce If you look at https://fr.wikibooks.org/wiki/Accueil, you see that the top categories.... are pointing to `Category:...` like links.

**Closed by kelson42** 2022-09-19 09:00 UTC
Labels: duplicate, question
