### ISSUE TITLE
No article titles in newest English wikiquote and wikiversity zim files

### ISSUE THREAD

**Issue by pyroshroom** [openzim/mwoffliner#565] opened 2019-02-16 23:10 UTC
The most recent .zim files for English wikiquote (wikiquote_en_all_novid_2019-02.zim) and wikiversity (wikiversity_en_all_novid_2019-02.zim) no longer display the large article title at beginning of the article itself. 

The article titles are still shown within the articles of the 100 article English Wikipedia from January. (wikipedia_en_100_2019-01.zim) 

Images examples:
Wikiquote En 2019-02: http://imgur.com/jQDjQK8
100 article Wikipedia En 2019-01: http://imgur.com/AqchIWi

**Comment by pyroshroom** [comment] 2019-03-06 23:52
The lack of article titles is still an issue for the most recent english Wikiquote (wikiquote_en_all_novid_2019-03.zim).

Additionally, the newest wikinews zim (wikinews_en_all_novid_2019-03.zim) has no titles now too, which makes it especially non-functional, as the news article title is typically not mentioned within the article itself, and the article just begins with the bolded date.

However, the latest wikivoyage (wikivoyage_en_all_novid_2019-03.zim) has working article titles, so would it be the settings for zim file creation that are the real problem?

**Comment by kelson42** [comment] 2019-03-07 05:14
@pyroshroom Thx for the feedback, give us a few days to get a proper answer about what went wrong here.

**Comment by kelson42** [comment] 2019-03-15 11:13
@pyroshroom I can confirm that this bug is fixed in mwoffliner 1.8 to be published ASAP. You can test it by installing from Github. Sorry for what looks like to be a regression introduced in 1.7.

**Closed by kelson42** 2019-03-15 11:13 UTC
Labels: bug
