### ISSUE TITLE
Same number of articles

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1541] opened 2021-09-19 13:28 UTC
Check, please.
In my opinion, **ru-all-maxi-Wikipedia** for **January** and **March** of this year has the same number of articles.
How can this be?
In my opinion, the number of articles should be different!
Check, please.

**Comment by kelson42** [comment] 2021-09-19 14:19
Duplicate of #1535

**Closed by kelson42** 2021-09-19 14:19 UTC
Labels: duplicate, question, wikimedia
