### ISSUE TITLE
audio files present in zim file, but not in article

### ISSUE THREAD

**Issue by uriesk** [openzim/mwoffliner#1765] opened 2023-02-02 12:18 UTC
Scrap an article with an ogg audio file [like this one](https://en.wikipedia.org/wiki/Read_my_lips:_no_new_taxes):

```
npm start -- --adminEmail=contact@kiwix.org --articleList=Read_my_lips:_no_new_taxes --mwUrl=https://en.wikipedia.org/ --webp
```

In the resulting zim file, the audio is not in the article.
But the ogg file is visible in zimdum.
Tested this with current dev and with 1.11.12. It is the same in both cases.

**Comment by kelson42** [comment] 2023-02-02 13:03
@pavel-karatsiuba I wonder how this is possible it works (now) with OGA, but not OGG file. Can you please look and fix?

**Comment by pavel-karatsiuba** [comment] 2023-02-02 17:02
The scraper removes all elements with "noprint" class from HTML. In this case, the "ogg player" parent container has "noprint" class. So it is removed and that's why you can't see it.

**Comment by kelson42** [comment] 2023-02-05 07:13
This is actually a duplicate of #849.

There is two discussions here IMO:
* Should we really remove it?
* If we remove it we should not download the audio file #849

**Closed** 2023-02-18 15:53 UTC
Labels: bug
