### ISSUE TITLE
Unable to setup the project due to problems with native build 

### ISSUE THREAD

**Issue by maskaravivek** [openzim/mwoffliner#1028] opened 2020-01-19 08:40 UTC
Hello, 

I am trying to set up this project on my ubuntu machine but am running into an error while running the `npm ci` command. Here are the logs for the error that I get. 

```
/home/ubuntu/.cache/node-gyp/13.6.0/include/node/v8.h:2773:39: note:   candidate expects 1 argument, 0 provided
nbind.target.mk:141: recipe for target 'Release/obj.target/nbind/../../../../nbind/src/common.o' failed
make: *** [Release/obj.target/nbind/../../../../nbind/src/common.o] Error 1
make: Leaving directory '/home/ubuntu/mwoffliner/node_modules/@openzim/libzim/build/native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-1051-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v13.6.0/bin/node" "/home/ubuntu/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "-C" "build/native" "configure" "build"
gyp ERR! cwd /home/ubuntu/mwoffliner/node_modules/@openzim/libzim/build/native
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @openzim/libzim@2.1.0 build:native: `autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @openzim/libzim@2.1.0 build:native script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-01-19T08_34_31_788Z-debug.log
Warning: problems with native build

> mwoffliner@1.9.14 prepublish /home/ubuntu/mwoffliner
> npm run build
```

Here are the full logs if that might be helpful. 

https://gist.github.com/maskaravivek/78322ff8b10534f2c26fe304d90aa63c

Moreover, my node and npm versions are: 

npm: 6.13.4
node: v13.6.0

Also, here are the details of my machine: 

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
```

Is there something that I am missing? I followed the installation steps that are mentioned in the readme file.

**Comment by kelson42** [comment] 2020-01-19 08:43
@maskaravivek You need nodejs10.

**Comment by kelson42** [comment] 2020-02-22 14:48
No feedback and this is basically a duplicate of #707

**Closed by kelson42** 2020-02-22 14:48 UTC
Labels: bug, question

**Comment by biswajitpatra** [comment] 2020-02-25 20:43
@kelson42 i am getting the same error but rather using a LTS version of node(12.16.1)

**Comment by LakmaNeha** [comment] 2020-03-02 16:10
> @maskaravivek You need nodejs10. Let me know if it works better please.

Here's the log

> 0 info it worked if it ends with ok
1 verbose cli [ '/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/node',
1 verbose cli   '/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:native' ]
2 info using npm@6.4.1
3 info using node@v11.0.0
4 verbose run-script [ 'prebuild:native', 'build:native', 'postbuild:native' ]
5 info lifecycle @openzim/libzim@2.1.0~prebuild:native: @openzim/libzim@2.1.0
6 info lifecycle @openzim/libzim@2.1.0~build:native: @openzim/libzim@2.1.0
7 verbose lifecycle @openzim/libzim@2.1.0~build:native: unsafe-perm in lifecycle true
8 verbose lifecycle @openzim/libzim@2.1.0~build:native: PATH: /Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim/node_modules/.bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/.bin:/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim/node_modules/.bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/.bin:/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin:/Users/srikarchowdavarapu/.rvm/gems/ruby-2.6.3/bin:/Users/srikarchowdavarapu/.rvm/gems/ruby-2.6.3@global/bin:/Users/srikarchowdavarapu/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/srikarchowdavarapu/.rvm/bin
9 verbose lifecycle @openzim/libzim@2.1.0~build:native: CWD: /Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim
10 silly lifecycle @openzim/libzim@2.1.0~build:native: Args: [ '-c',
10 silly lifecycle   'autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist' ]
11 silly lifecycle @openzim/libzim@2.1.0~build:native: Returned: code: 1  signal: null
12 info lifecycle @openzim/libzim@2.1.0~build:native: Failed to exec build:native script
13 verbose stack Error: @openzim/libzim@2.1.0 build:native: `autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @openzim/libzim@2.1.0
15 verbose cwd /Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim
16 verbose Darwin 18.7.0
17 verbose argv "/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/node" "/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/npm" "run" "build:native"
18 verbose node v11.0.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @openzim/libzim@2.1.0 build:native: `autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist`
22 error Exit status 1
23 error Failed at the @openzim/libzim@2.1.0 build:native script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


@kelson42 tried with node version 10 and 11 as well, doesn't seem to work. Please let me know if there is anything else I can do to setup this in my local. Thanks.

**Comment by LakmaNeha** [comment] 2020-03-02 16:12
> @maskaravivek You need nodejs10. Let me know if it works better please.

Here's the log

> 0 info it worked if it ends with ok
1 verbose cli [ '/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/node',
1 verbose cli   '/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:native' ]
2 info using npm@6.4.1
3 info using node@v11.0.0
4 verbose run-script [ 'prebuild:native', 'build:native', 'postbuild:native' ]
5 info lifecycle @openzim/libzim@2.1.0~prebuild:native: @openzim/libzim@2.1.0
6 info lifecycle @openzim/libzim@2.1.0~build:native: @openzim/libzim@2.1.0
7 verbose lifecycle @openzim/libzim@2.1.0~build:native: unsafe-perm in lifecycle true
8 verbose lifecycle @openzim/libzim@2.1.0~build:native: PATH: /Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim/node_modules/.bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/.bin:/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim/node_modules/.bin:/Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/.bin:/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin:/Users/srikarchowdavarapu/.rvm/gems/ruby-2.6.3/bin:/Users/srikarchowdavarapu/.rvm/gems/ruby-2.6.3@global/bin:/Users/srikarchowdavarapu/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/srikarchowdavarapu/.rvm/bin
9 verbose lifecycle @openzim/libzim@2.1.0~build:native: CWD: /Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim
10 silly lifecycle @openzim/libzim@2.1.0~build:native: Args: [ '-c',
10 silly lifecycle   'autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist' ]
11 silly lifecycle @openzim/libzim@2.1.0~build:native: Returned: code: 1  signal: null
12 info lifecycle @openzim/libzim@2.1.0~build:native: Failed to exec build:native script
13 verbose stack Error: @openzim/libzim@2.1.0 build:native: `autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @openzim/libzim@2.1.0
15 verbose cwd /Users/srikarchowdavarapu/Desktop/personal/mwoffliner/node_modules/@openzim/libzim
16 verbose Darwin 18.7.0
17 verbose argv "/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/node" "/Users/srikarchowdavarapu/.nvm/versions/node/v11.0.0/bin/npm" "run" "build:native"
18 verbose node v11.0.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @openzim/libzim@2.1.0 build:native: `autogypi -r build && node-gyp -C build/native configure build && copyasm build/native dist`
22 error Exit status 1
23 error Failed at the @openzim/libzim@2.1.0 build:native script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


@kelson42 tried with node version 10 and 11 as well, doesn't seem to work. Please let me know if there is anything else I can do to setup this in my local. Thanks.

**Comment by kelson42** [comment] 2020-03-02 17:16
@LakmaNeha Please open a new ticket, this ticket was for nodejs12 and is closed.
