### ISSUE TITLE
js errors in javascript console

### ISSUE THREAD

**Issue by tim-moody** [openzim/mwoffliner#1242] opened 2020-07-28 13:57 UTC
I always see js errors in the javascript console in both chrome and firefox. This one is from wikipedia_en_medicine_2020-05 on accessing the first page with kiwix-serve, but I believe you will see it with any zim. This has been here for quite a long time. I should have reported it before.

```
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. jquery.js:9574:13
Uncaught SyntaxError: expected expression, got end of script
jsConfigVars.js:1:1
Uncaught SyntaxError: unexpected token: '.'
startup.js:11:28
JQMIGRATE: Migrate is installed with logging active, version 3.1.0 jquery.js:144:171
Uncaught ReferenceError: mw is not defined
    <anonymous> jQuery
jquery.js:156:1
Uncaught ReferenceError: mw is not defined
    <anonymous> http://iiab-devel/kiwix/wikipedia_en_medicine_2020-05/-/j/js_modules/mediawiki.js:1
mediawiki.js:1:1
Uncaught ReferenceError: mw is not defined
    <anonymous> http://iiab-devel/kiwix/wikipedia_en_medicine_2020-05/-/j/js_modules/site.js:1
site.js:1:1
```
​

**Comment by kelson42** [comment] 2020-07-28 14:15
Basically a duplicate of #894

**Closed by kelson42** 2020-07-28 14:15 UTC
Labels: bug, duplicate, wikimedia
