### ISSUE TITLE
Other namespaces link should be removed

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#1064] opened 2020-03-30 12:38 UTC
Links to pages in a different namespace (and not added with `--add-namespaces`) are not removed resulting in not only dead links but unclear errors:

![Screen Shot 2020-03-30 at 12 34 00](https://user-images.githubusercontent.com/57929/77912797-be2a9c80-7282-11ea-84d6-2ea198dc8a33.png)

That's because links to other namespace are in the form `Namespace:ArticleName` which the browser interprets as an unhandled scheme.

Lots of examples in [Wikibooks home page](http://library.kiwix.org/wikibooks_fr_all_maxi/A/Accueil) (to `wikilivres:Vitrine` for instance)

I believe those links should be removed as we do for not-included articles.

Here is the recipe: https://farm.openzim.org/recipes/wikibooks_fr/config

@Popolechien, for `wikibooks_fr`, maybe we want to add the `4`/`wikilivres` namespace to the recipe?

**Comment by kelson42** [comment] 2020-03-30 12:53
OK, this is definitely a regression if this is confirmed.

**Comment by rgaudin** [comment] 2020-03-30 13:17
you can check it online. ZIM is 2020-03

**Comment by kelson42** [comment] 2020-05-11 19:13
I suspect we have fixed that bug in `master`. Might be a duplicate of  #1095

**Comment by kelson42** [comment] 2020-05-12 09:37
Fixed with #1095

**Closed by kelson42** 2020-05-12 09:37 UTC
Labels: bug
