### ISSUE TITLE
FATAL - Failed to get MediaWiki Metadata

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#649] opened 2019-04-02 04:08 UTC
Exit code: 2
Command: `mwoffliner --mwUrl=https://ab.wiktionary.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --useCache --redis=redis://redis --outputDirectory=/output`

stderr:
```
[error] [2019-04-02T04:05:25.902Z] FATAL - Failed to get MediaWiki Metadata
Failed to run mwoffliner after [4s]: { Error: Request failed with status code 404
    at createError (/usr/local/lib/node_modules/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/mwoffliner/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/usr/local/lib/node_modules/mwoffliner/node_modules/axios/lib/adapters/http.js:201:11)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 60000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        accept:
         'text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"',
        'cache-control': 'public, max-stale=2678400',
        'accept-encoding': 'gzip, deflate',
        'user-agent': 'MWOffliner/HEAD (contact@kiwix.org)',
        cookie: '' },
     method: 'get',
     url: 'https://ab.wiktionary.org/wiki/',
     responseType: 'arraybuffer',
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'ab.wiktionary.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'ab.wiktionary.org',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        write: [Function: writeAfterFIN],
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 729,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 8300,
        [Symbol(kBytesWritten)]: 366,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'ab.wiktionary.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'ab.wiktionary.org',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        write: [Function: writeAfterFIN],
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 729,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 8300,
        [Symbol(kBytesWritten)]: 366,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET /wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0 HTTP/1.1\r\naccept: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"\r\ncache-control: public, max-stale=2678400\r\naccept-encoding: gzip, deflate\r\nuser-agent: MWOffliner/HEAD (contact@kiwix.org)\r\ncookie: \r\nHost: ab.wiktionary.org\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path:
      '/wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 404,
        statusMessage: 'Not Found',
        client: [TLSSocket],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl:
         'https://ab.wiktionary.org/wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 1,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl:
         'https://ab.wiktionary.org/wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0',
        _isRedirect: true },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'cache-control': [Array],
        'accept-encoding': [Array],
        'user-agent': [Array],
        cookie: [Array],
        host: [Array] } },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers:
      { date: 'Tue, 02 Apr 2019 04:05:25 GMT',
        'content-type': 'text/html; charset=UTF-8',
        'content-length': '6064',
        connection: 'close',
        server: 'mw1256.eqiad.wmnet',
        'x-content-type-options': 'nosniff',
        p3p:
         'CP="This is not a P3P policy! See https://ab.wiktionary.org/wiki/%D0%A6%D0%B0%D1%81%D1%82%D3%99%D0%B8:CentralAutoLogin/P3P for more info."',
        'x-powered-by': 'HHVM/3.18.6-dev',
        'content-language': 'ab',
        'content-security-policy-report-only':
         'script-src \'unsafe-eval\' \'self\' meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org \'unsafe-inline\'; default-src \'self\' data: blob: upload.wikimedia.org https://commons.wikimedia.org meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org wikimedia.org; style-src \'self\' data: blob: upload.wikimedia.org https://commons.wikimedia.org meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org wikimedia.org \'unsafe-inline\'; report-uri /w/api.php?action=cspreport&format=json&reportonly=1&',
        'backend-timing': 'D=93490 t=1554177681396618',
        vary: 'Accept-Encoding,Cookie,Authorization,X-Seven',
        'x-varnish': '486584246 468382358, 576021306 573536755',
        via: '1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1)',
        age: '244',
        'x-cache': 'cp1085 hit/1, cp1079 hit/11',
        'x-cache-status': 'hit-front',
        'server-timing': 'cache;desc="hit-front"',
        'strict-transport-security': 'max-age=106384710; includeSubDomains; preload',
        'set-cookie': [Array],
        'x-analytics': 'https=1',
        'x-client-ip': '172.16.7.219',
        'cache-control': 'private, s-maxage=0, max-age=0, must-revalidate' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 60000,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        url: 'https://ab.wiktionary.org/wiki/',
        responseType: 'arraybuffer',
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0 HTTP/1.1\r\naccept: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"\r\ncache-control: public, max-stale=2678400\r\naccept-encoding: gzip, deflate\r\nuser-agent: MWOffliner/HEAD (contact@kiwix.org)\r\ncookie: \r\nHost: ab.wiktionary.org\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path:
         '/wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 3c 68 74 6d 6c 20 63 6c 61 73 73 3d 22 63 6c 69 65 6e 74 2d 6e 6f 6a 73 22 20 6c 61 6e 67 3d 22 61 62 ... > } }


**********

Request failed with status code 404

**********



```

**Comment by ISNIT0** [comment] 2019-04-02 06:17
This isn't a bug `https://ab.wiktionary.org/wiki` gives a 404, can you set a different `--mwWikiPath` please

**Comment by automactic** [comment] 2019-04-02 10:58
what `mwWikiPath` should I use? `api.php`?

**Comment by kelson42** [comment] 2019-04-02 20:01
@ISNIT0 It does not give 404. Please systematically check this kind of things in details, for example with `curl`. What @automactic is an absolute Wikimedia wiki scraping command. This should work.
```
$ curl -I https://ab.wiktionary.org/wiki
HTTP/2 301 
date: Tue, 02 Apr 2019 19:59:26 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: https://ab.wiktionary.org/wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0
server: mw1239.eqiad.wmnet
x-powered-by: HHVM/3.18.6-dev
p3p: CP="This is not a P3P policy! See https://ab.wiktionary.org/wiki/%D0%A6%D0%B0%D1%81%D1%82%D3%99%D0%B8:CentralAutoLogin/P3P for more info."
cache-control: s-maxage=1200, must-revalidate, max-age=0
x-content-type-options: nosniff
last-modified: Tue, 02 Apr 2019 19:59:18 GMT
backend-timing: D=35466 t=1554235158471208
vary: Accept-Encoding,X-Forwarded-Proto,Cookie,Authorization,X-Seven
x-varnish: 315033579, 1012353230, 974218282 984040240
via: 1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1)
age: 8
x-cache: cp1085 pass, cp3041 miss, cp3032 hit/1
x-cache-status: hit-front
server-timing: cache;desc="hit-front"
strict-transport-security: max-age=106384710; includeSubDomains; preload
```

**Comment by ISNIT0** [comment] 2019-04-02 20:06
WGET:
```
➜  ~ wget https://ab.wiktionary.org/wiki
--2019-04-02 22:04:28--  https://ab.wiktionary.org/wiki
Resolving ab.wiktionary.org (ab.wiktionary.org)... 91.198.174.192
Connecting to ab.wiktionary.org (ab.wiktionary.org)|91.198.174.192|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://ab.wiktionary.org/wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0 [following]
--2019-04-02 22:04:28--  https://ab.wiktionary.org/wiki/%D0%98%D1%85%D0%B0%D0%B4%D0%BE%D1%83_%D0%90%D0%B4%D0%B0%D2%9F%D1%8C%D0%B0
Reusing existing connection to ab.wiktionary.org:443.
HTTP request sent, awaiting response... 404 Not Found
2019-04-02 22:04:28 ERROR 404: Not Found.
```

This is probably the same/similar to https://github.com/openzim/mwoffliner/issues/623

**Comment by kelson42** [comment] 2019-04-07 20:59
@ISNIT0 Yes, this is clearly a duplicate of #623. These wiki should not be mirrored.

**Closed by kelson42** 2019-04-07 20:59 UTC
Labels: bug
