### ISSUE TITLE
Create zim of https://zdoom.org/w/

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#86] opened 2017-05-30 06:11 UTC
Following popular request...

**Comment by kelson42** [comment] 2017-05-30 06:14
Old ticket about zdoom https://sourceforge.net/p/kiwix/feature-requests/644/

**Comment by kelson42** [comment] 2018-01-12 23:27
```
./bin/mwoffliner.script.js --format= --withZimFullTextIndex --adminEmail=contact@kiwix.org --deflateTmpHtml --verbose --skipHtmlCache --skipCacheCleaning  --mwUrl=https://zdoom.org --localParsoid --mwWikiPath=wiki --speed=0.1 --articleList=articles
```

Seems impossible to offline "Hierarchical_class_list"

**Comment by Popolechien** [comment] 2018-01-13 15:01
Well then close?

**Comment by kelson42** [comment] 2018-01-14 16:57
@Popolechien No, I want to understand why this article can not be rendered properly by Parsoid... or the system running Parsoid.
@subbuss Here is the test/log failing. Can you reproduce it?

```
$ echo "Hierarchical_class_list" > articles && ./bin/mwoffliner.script.js --format= --withZimFullTextIndex --adminEmail=contact@kiwix.org --deflateTmpHtml --verbose --skipHtmlCache --skipCacheCleaning  --mwUrl=https://zdoom.org --localParsoid --mwWikiPath=wiki --speed=0.1 --articleList=articles
Starting Parsoid
info loading ...
info ready on :8000
Parsoid Started Successfully
Getting text direction...
Downloading https://zdoom.org/wiki/...
Text direction is ltr
Getting web site name...
Downloading https://zdoom.org/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc...
Getting sub-title...
Downloading https://zdoom.org/wiki/...
Downloading https://zdoom.org/w/api.php?action=query&meta=siteinfo&siprop=namespaces|namespacealiases&format=json...
Creating base directories...
Preparing cache...
Downloading https://zdoom.org/w/api.php?action=query&redirects&format=json&prop=revisions|coordinates&titles=Hierarchical_class_list...
Getting redirects for article Hierarchical_class_list...
Downloading https://zdoom.org/w/api.php?action=query&list=backlinks&blfilterredir=redirects&bllimit=max&format=json&bltitle=Hierarchical_class_list&rawcontinue=...
List of article ids to mirror completed
0 redirect(s) found for Hierarchical_class_list
All redirect ids retrieve successfuly.
Reset redirects cache file (or create it)
Caching redirects...
All redirects were cached successfuly.
Starting a new dump...
Creating sub directories at "/tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/"...
Dumping stylesheets...
Cache hit for https://zdoom.org/wiki/ (/tmp/mwoffliner/cac/zdoom_en/8d7489ff19f67ee96f18)
Downloading CSS from http://zdoom.org/w/load.php?debug=false&lang=en&modules=mediawiki.legacy.commonPrint%2Cshared|mediawiki.sectionAnchor|mediawiki.skinning.interface|skins.vector.styles&only=styles&skin=vector
Downloading http://zdoom.org/w/load.php?debug=false&lang=en&modules=mediawiki.legacy.commonPrint%2Cshared|mediawiki.sectionAnchor|mediawiki.skinning.interface|skins.vector.styles&only=styles&skin=vector...
Downloading CSS from http://zdoom.org/w/load.php?debug=false&lang=en&modules=site.styles&only=styles&skin=vector
Downloading http://zdoom.org/w/load.php?debug=false&lang=en&modules=site.styles&only=styles&skin=vector...
Downloading http://zdoom.org/w/resources/src/mediawiki.legacy/images/ajax-loader.gif?57f34 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/ajax-loader.gif...
Downloading http://zdoom.org/w/resources/src/mediawiki.legacy/images/ajax-loader.gif?57f34...
Downloading http://zdoom.org/w/resources/src/mediawiki.legacy/images/spinner.gif?ca65b at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/spinner.gif...
Downloading http://zdoom.org/w/resources/src/mediawiki.legacy/images/spinner.gif?ca65b...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/ajax-loader.gif
Downloading CSS from https://zdoom.org/wiki/Mediawiki:offline.css?action=raw
Downloading https://zdoom.org/wiki/Mediawiki:offline.css?action=raw...
Downloading http://zdoom.org/w/resources/src/mediawiki.skinning/images/magnify-clip-ltr.png?4f704 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/magnify-clip-ltr.png...
Downloading http://zdoom.org/w/resources/src/mediawiki.skinning/images/magnify-clip-ltr.png?4f704...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/spinner.gif
Unable to download content [1] https://zdoom.org/wiki/Mediawiki:offline.css?action=raw (statusCode=404).
Downloading http://zdoom.org/w/resources/src/mediawiki.skinning/images/magnify-clip-rtl.png?a9fb3 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/magnify-clip-rtl.png...
Downloading http://zdoom.org/w/resources/src/mediawiki.skinning/images/magnify-clip-rtl.png?a9fb3...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/magnify-clip-ltr.png
Downloading http://zdoom.org/w/images/wikilogo.png?f4341 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/wikilogo.png...
Downloading http://zdoom.org/w/images/wikilogo.png?f4341...
Unable to download content [2] https://zdoom.org/wiki/Mediawiki:offline.css?action=raw (statusCode=404).
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/magnify-clip-rtl.png
Downloading http://zdoom.org/w/skins/Vector/images/bullet-icon.png?e31f8 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/bullet-icon.png...
Downloading http://zdoom.org/w/skins/Vector/images/bullet-icon.png?e31f8...
Downloading http://zdoom.org/w/skins/Vector/images/user-icon.png?13155 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/user-icon.png...
Downloading http://zdoom.org/w/skins/Vector/images/user-icon.png?13155...
Unable to download content [3] https://zdoom.org/wiki/Mediawiki:offline.css?action=raw (statusCode=404).
Absolutely unable to retrieve async. URL: Unable to download content [3] https://zdoom.org/wiki/Mediawiki:offline.css?action=raw (statusCode=404).
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/bullet-icon.png
Downloading http://zdoom.org/w/skins/Vector/images/search-fade.png?50f7b at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/search-fade.png...
Downloading http://zdoom.org/w/skins/Vector/images/search-fade.png?50f7b...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/user-icon.png
Downloading http://zdoom.org/w/skins/Vector/images/search-ltr.png?39f97 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/search-ltr.png...
Downloading http://zdoom.org/w/skins/Vector/images/search-ltr.png?39f97...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/search-fade.png
Downloading http://zdoom.org/w/skins/Vector/images/tab-break.png?09d4b at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/tab-break.png...
Downloading http://zdoom.org/w/skins/Vector/images/tab-break.png?09d4b...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/search-ltr.png
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/wikilogo.png
Downloading http://zdoom.org/w/skins/Vector/images/tab-normal-fade.png?1cc52 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/tab-normal-fade.png...
Downloading http://zdoom.org/w/skins/Vector/images/tab-normal-fade.png?1cc52...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/tab-break.png
Downloading http://zdoom.org/w/skins/Vector/images/tab-current-fade.png?22887 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/tab-current-fade.png...
Downloading http://zdoom.org/w/skins/Vector/images/tab-current-fade.png?22887...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/tab-normal-fade.png
Downloading http://zdoom.org/w/skins/Vector/images/arrow-down-icon.png?d72f0 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/arrow-down-icon.png...
Downloading http://zdoom.org/w/skins/Vector/images/arrow-down-icon.png?d72f0...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/tab-current-fade.png
Downloading http://zdoom.org/w/skins/Vector/images/arrow-down-focus-icon.png?69899 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/arrow-down-focus-icon.png...
Downloading http://zdoom.org/w/skins/Vector/images/arrow-down-focus-icon.png?69899...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/arrow-down-icon.png
Downloading http://zdoom.org/w/skins/Vector/images/unwatch-icon.png?fccbe at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/unwatch-icon.png...
Downloading http://zdoom.org/w/skins/Vector/images/unwatch-icon.png?fccbe...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/arrow-down-focus-icon.png
Downloading http://zdoom.org/w/skins/Vector/images/watch-icon.png?e1b42 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/watch-icon.png...
Downloading http://zdoom.org/w/skins/Vector/images/watch-icon.png?e1b42...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/unwatch-icon.png
Downloading http://zdoom.org/w/skins/Vector/images/unwatch-icon-hl.png?c4723 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/unwatch-icon-hl.png...
Downloading http://zdoom.org/w/skins/Vector/images/unwatch-icon-hl.png?c4723...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/watch-icon.png
Downloading http://zdoom.org/w/skins/Vector/images/watch-icon-hl.png?f4c7e at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/watch-icon-hl.png...
Downloading http://zdoom.org/w/skins/Vector/images/watch-icon-hl.png?f4c7e...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/unwatch-icon-hl.png
Downloading http://zdoom.org/w/skins/Vector/images/watch-icon-loading.png?5cb92 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/watch-icon-loading.png...
Downloading http://zdoom.org/w/skins/Vector/images/watch-icon-loading.png?5cb92...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/watch-icon-hl.png
Downloading http://zdoom.org/w/skins/Vector/images/page-fade.png?1d168 at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/page-fade.png...
Downloading http://zdoom.org/w/skins/Vector/images/page-fade.png?1d168...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/watch-icon-loading.png
Downloading http://zdoom.org/w/skins/Vector/images/portal-break.png?3ea1b at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/portal-break.png...
Downloading http://zdoom.org/w/skins/Vector/images/portal-break.png?3ea1b...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/page-fade.png
Downloading http://zdoom.org/w/skins/Vector/images/external-link-ltr-icon.png?325de at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/external-link-ltr-icon.png...
Downloading http://zdoom.org/w/skins/Vector/images/external-link-ltr-icon.png?325de...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/portal-break.png
Saving favicon.png...
Downloading https://zdoom.org/w/api.php?action=query&meta=siteinfo&format=json...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/s/external-link-ltr-icon.png
Downloading https://zdoom.org/w/images/wikilogo.png at /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/favicon.png...
Downloading https://zdoom.org/w/images/wikilogo.png...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/favicon.png
Creating main page...
Saving articles...
Getting (desktop) article from http://localhost:8000/zdoom.org/v3/page/pagebundle/Hierarchical_class_list?oldid=35159
Downloading http://localhost:8000/zdoom.org/v3/page/pagebundle/Hierarchical_class_list?oldid=35159...
Successfuly optimized /tmp/mwoffliner/tmp/zdoom_en_articles_2018-01/favicon.png
error/api/version { logType: 'error/api/version',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"',
  longMsg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"' }
info { logType: 'info',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: 35159,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'redirecting to revision 35159 for pagebundle',
  longMsg: 'redirecting to revision\n35159\nfor\npagebundle' }
error/api/version { logType: 'error/api/version',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"',
  longMsg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"' }
info { logType: 'info',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: 35159,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'started parsing',
  longMsg: 'started parsing' }

^Ainfo { logType: 'info',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: 35159,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'completed parsing in 120122 ms',
  longMsg: 'completed parsing in 120122 ms' }
Unable to download content [1] http://localhost:8000/zdoom.org/v3/page/pagebundle/Hierarchical_class_list?oldid=35159 (request error: Error: socket hang up ).
error/api/version { logType: 'error/api/version',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"',
  longMsg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"' }
info { logType: 'info',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: 35159,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'redirecting to revision 35159 for pagebundle',
  longMsg: 'redirecting to revision\n35159\nfor\npagebundle' }
error/api/version { logType: 'error/api/version',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"',
  longMsg: 'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.5.0"' }
info { logType: 'info',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: 35159,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'started parsing',
  longMsg: 'started parsing' }
info { logType: 'info',
  wiki: 'wiki$0',
  title: 'Hierarchical_class_list',
  oldId: 35159,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (contact@kiwix.org)',
  msg: 'completed parsing in 120924 ms',
  longMsg: 'completed parsing in 120924 ms' }
Unable to download content [2] http://localhost:8000/zdoom.org/v3/page/pagebundle/Hierarchical_class_list?oldid=35159 (request error: Error: socket hang up ).
```

**Comment by subbuss** [comment] 2018-01-14 17:04
```
 msg: 'completed parsing in 120924 ms',
  longMsg: 'completed parsing in 120924 ms' }
Unable to download content [2] http://localhost:8000/zdoom.org/v3/page/pagebundle/Hierarchical_class_list?oldid=35159 (request error: Error: socket hang up
```
Looks like mwoffliner is timing out and closing the socket because it is taking > 2 mins to parse that page?

**Comment by kelson42** [comment] 2018-01-14 17:06
@subbuss I'm already running that with the branch `improved_timeouts`, what can I do more?

**Comment by kelson42** [comment] 2018-09-18 10:16
This issue was moved to openzim/zim-requests#98

**Closed by kelson42** 2018-09-18 10:16 UTC
Labels: ZIM
