### ISSUE TITLE
There is no links to renamed articles

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1269] opened 2020-10-04 15:02 UTC
**wikipedia_ru_all_maxi_2020-07.zim**

This zim file contains **all the articles**.
Open an article about **[Paper](https://ru.wikipedia.org/wiki/Бумага#См._также)**.
And we see that the fourth line is written just text without a link:
![Kiwix-2-8-0-firefox](https://user-images.githubusercontent.com/65112331/95018838-cf59c900-066a-11eb-82bc-8256d52862d8.gif)

But the article exists! It was just renamed and now it is called **[Целлюлозно-бумажное производство](https://ru.wikipedia.org/wiki/Целлюлозно-бумажное_производство)**.
And the article is in the zim file itself. But the link to it is missing due to the fact that the article is now called differently.

This is what a link looks like in a web browser:
![WebBrowser](https://user-images.githubusercontent.com/65112331/95018857-dbde2180-066a-11eb-9b7f-8f3eba1e9401.gif)

This is just one example. I think that in the zim files of the English Wikipedia there are also no links to renamed articles.

**Comment by Ubuntu-2020** [comment] 2020-10-14 11:28
The article by **[Kevin Jarre](https://library.kiwix.org/wikipedia_en_all_maxi_2020-09/A/Kevin_Jarre)**.
The link to the article about **Detroit, Michigan** is not visible. The link is not visible due to the fact that the **Detroit, Michigan** article was renamed to **Detroit**:
![Redirected from Detroit, Michigan](https://user-images.githubusercontent.com/65112331/95982255-92d75b80-0e28-11eb-8ccf-b77e6c990858.gif)

Here's what [Kevin Jarre](https://en.wikipedia.org/wiki/Kevin_Jarre#Background)'s article looks like in a web browser
![Redirected from Detroit, Michigan-in-web-browser-is-visible](https://user-images.githubusercontent.com/65112331/95982227-88b55d00-0e28-11eb-9449-030a4ff5f5d0.gif)

**Comment by kelson42** [comment] 2020-10-30 18:58
Strongly suspect this is a duplicate of #1289

**Comment by MananJethwani** [comment] 2020-10-30 20:39
yeah seems to be the same problem

**Comment by kelson42** [comment] 2020-10-31 12:42
Closing as duplicate. Will be fixed in the next days.

**Closed by kelson42** 2020-10-31 12:42 UTC
Labels: bug, wikimedia
