### ISSUE TITLE
Wikinews ZIMs of July only contain one article

### ISSUE THREAD

**Issue by hashworks** [openzim/mwoffliner#1210] opened 2020-07-17 08:47 UTC
Drastic decrease in size, seem to be broken:
```
wikinews_de_all_maxi_2020-06.zim  2020-06-02 11:29   78M   
wikinews_de_all_maxi_2020-07.zim  2020-07-03 12:05  387K   
wikinews_de_all_nopic_2020-06.zim 2020-06-02 11:22   43M   
wikinews_de_all_nopic_2020-07.zim 2020-07-03 12:04  278K
[...]
wikinews_en_all_maxi_2020-06.zim  2020-06-02 12:03  201M   
wikinews_en_all_maxi_2020-07.zim  2020-07-03 12:04  6.5M   
wikinews_en_all_nopic_2020-06.zim 2020-06-02 11:51   82M   
wikinews_en_all_nopic_2020-07.zim 2020-07-03 12:04  6.5M  
````

https://download.kiwix.org/zim/wikinews/

![example](https://fb.hash.works/e8xQM/)

**Comment by Popolechien** [comment] 2020-08-26 09:48
Duplicate of #1230

**Closed by Popolechien** 2020-08-26 09:48 UTC
Labels: bug, duplicate
