### ISSUE TITLE
[REGRESSION] Stuck offlining ar.wikipedia.org

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#685] opened 2019-04-18 03:45 UTC
mwoffliner version 1.8.3

section of docker inspect
```
"Id": "f5e3b2ab0146a5d4f5b1d8e9142c204de71cd8bd4badeabea56a987187634f44",
"Created": "2019-04-17T23:44:49.35616106Z",
"Path": "mwoffliner",
"Args": [
    "--mwUrl=https://ar.wikipedia.org",
    "--adminEmail=contact@kiwix.org",
    "--format=nopic",
    "--format=novid",
    "--useCache",
    "--customMainPage=مستخدم:Stephane_(Kiwix)/Landing",
    "--redis=redis://redis",
    "--outputDirectory=/output"
],
"State": {
    "Status": "running",
    "Running": true,
    "Paused": false,
    "Restarting": false,
    "OOMKilled": false,
    "Dead": false,
    "Pid": 30405,
    "ExitCode": 0,
    "Error": "",
    "StartedAt": "2019-04-17T23:44:49.883207762Z",
    "FinishedAt": "0001-01-01T00:00:00Z"
},
```

stdout (that's all there is)
```
[log] [2019-04-17T23:44:50.849Z] Getting text direction...
[log] [2019-04-17T23:44:50.851Z] Getting site info...
[log] [2019-04-17T23:44:50.851Z] Getting sub-title...
[log] [2019-04-17T23:44:51.041Z] Text direction is [rtl]
[log] [2019-04-17T23:44:51.165Z] Using a remote MCS instance
[log] [2019-04-17T23:44:51.176Z] Redis databases flushed.
[log] [2019-04-17T23:44:51.882Z] Got [196] articles from namespace [0]
[log] [2019-04-17T23:44:52.734Z] Got [224] articles from namespace [0]
```

**Comment by automactic** [comment] 2019-04-18 03:47
it is now 2019-04-18T03:45:27Z. stdout still didn't change. mem usage of the container is around 3.6GB, increasing at around 0.001GB/s. very little CPU utilization.

Not sure what to do, going to wait for 6-7 hours to see if anything has changed

**Comment by ISNIT0** [comment] 2019-04-18 10:01
Odd. I've never seen it freeze this early in the process.
I have managed to reproduce it though, and am working on the fix - looks like a bug in the query continuation logic when there are many redirects...

**Comment by ISNIT0** [comment] 2019-04-18 11:39
@automactic There is no need to leave it running any more, I don't think it will ever move forwards. I've identified and have a fix for the issue

**Comment by automactic** [comment] 2019-04-18 14:37
This issue seems to be wide spread. I am going to stop generating zim files using 1.8.3 for now. 

@ISNIT0 Do you think you can release a maintenance releases with just fix for this issue?

**Comment by ISNIT0** [comment] 2019-04-18 14:38
Yes, working on it

**Comment by ISNIT0** [comment] 2019-04-18 14:39
@automactic Aiming to release a fix tomorrow (will run UATs overnight)

**Comment by automactic** [comment] 2019-04-20 20:27
Sure this issue is fixed? Af far as I can tell, the issue still exists. (yes I am running 1.8.4)

ar.wikipedia.org
```
[log] [2019-04-20T20:26:00.874Z] Getting text direction...
[log] [2019-04-20T20:26:00.876Z] Getting site info...
[log] [2019-04-20T20:26:00.876Z] Getting sub-title...
[log] [2019-04-20T20:26:01.072Z] Text direction is [rtl]
[log] [2019-04-20T20:26:01.214Z] Using a remote MCS instance
[log] [2019-04-20T20:26:01.224Z] Redis databases flushed.
[log] [2019-04-20T20:26:02.087Z] Got [196] articles from namespace [0]
[log] [2019-04-20T20:26:02.901Z] Got [224] articles from namespace [0]
```

en.wikipedia.org:
```
[log] [2019-04-20T19:43:48.662Z] Getting text direction...
[log] [2019-04-20T19:43:48.665Z] Getting site info...
[log] [2019-04-20T19:43:48.665Z] Getting sub-title...
[log] [2019-04-20T19:43:48.876Z] Text direction is [ltr]
[log] [2019-04-20T19:43:48.892Z] Using a remote MCS instance
[log] [2019-04-20T19:43:48.907Z] Redis databases flushed.
[log] [2019-04-20T19:43:49.062Z] Got [39] articles from namespace [0]
[log] [2019-04-20T19:43:49.143Z] Got [36] articles from namespace [0]
[log] [2019-04-20T19:43:49.270Z] Got [30] articles from namespace [0]
[log] [2019-04-20T19:43:49.393Z] Got [26] articles from namespace [0]
[log] [2019-04-20T19:43:49.511Z] Got [30] articles from namespace [0]
[log] [2019-04-20T19:43:49.636Z] Got [41] articles from namespace [0]
[log] [2019-04-20T19:43:49.864Z] Got [89] articles from namespace [0]
```

ace.wikipeida.org
```
[log] [2019-04-20T19:41:34.820Z] Getting text direction...
[log] [2019-04-20T19:41:34.822Z] Getting site info...
[log] [2019-04-20T19:41:34.822Z] Getting sub-title...
[log] [2019-04-20T19:41:34.966Z] Text direction is [ltr]
[log] [2019-04-20T19:41:35.069Z] Using a remote MCS instance
[log] [2019-04-20T19:41:35.083Z] Redis databases flushed.
[log] [2019-04-20T19:41:35.616Z] Got [402] articles from namespace [0]
[log] [2019-04-20T19:41:36.095Z] Got [405] articles from namespace [0]
```

**Comment by ISNIT0** [comment] 2019-04-21 12:08
I was able to run the whole `ar`... :(

**Comment by ISNIT0** [comment] 2019-04-21 16:18
I've done a full scrape of `ace`, starting `ar` now

**Comment by ISNIT0** [comment] 2019-04-23 12:00
My scrape of `ar` froze (quite far into the scrape), I'm re-running it with verbose logging to diagnose the issue

**Comment by kelson42** [comment] 2019-04-26 14:54
@ISNIT0 What is the status on this?

**Comment by ISNIT0** [comment] 2019-04-26 16:47
I re-ran it twice without it freezing. I will try again once I've finished the UATs

**Comment by kelson42** [comment] 2019-04-29 20:11
@ISNIT0 @automactic What should we do with that issue? Should we test again on the zimfarm with 1.8.5?

**Comment by ISNIT0** [comment] 2019-05-10 17:26
@kelson42 I think it's worth retrying this now. I can't see any runs of this on ZimFarm

**Comment by kelson42** [comment] 2019-05-10 17:28
ok, will close it and reopen it if necessary.

**Closed by kelson42** 2019-05-10 17:28 UTC
Labels: bug
