### ISSUE TITLE
Error if there is a slash / at the beginning of the article

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1446] opened 2021-04-24 10:39 UTC
If you click on the word  **/bin** in the article [**Bin**](http://library.kiwix.org/wikipedia_ru_all_maxi_2021-03/A/Bin), you will see an error:
![bug](https://user-images.githubusercontent.com/65112331/115955815-ab27e180-a501-11eb-863f-5491d81dd79e.gif)

But **[this article](http://library.kiwix.org/wikipedia_ru_all_maxi_2021-03/A//bin)** is in the ZIM file!

The situation is similar with articles:

- /dev/random
- /dev/null
- /dev/zero
etc.

**Comment by kelson42** [comment] 2021-04-26 08:32
Duplicate of #1368

**Closed by kelson42** 2021-04-26 08:32 UTC
